### ISSUE TITLE
Python error of some sort

### ISSUE THREAD

**Issue by darth-untermensch** [librespot-org/librespot#1061]
**Describe the bug**
Add-on fails to launch

**To reproduce**
Install and enable librespot. UI displays "failed to start" error message

**Log**
```
2022-09-30 23:15:50.361 T:4543     INFO <general>: Librespot: monitor started
2022-09-30 23:15:50.365 T:4543    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'kodi'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/service.librespot/default.py", line 8, in <module>
                                                       Monitor().run()
                                                     File "/storage/.kodi/addons/service.librespot/resources/lib/ls_monitor.py", line 19, in run
                                                       librespot = Librespot()
                                                     File "/storage/.kodi/addons/service.librespot/resources/lib/ls_librespot.py", line 37, in __init__
                                                       settings = get_settings()
                                                     File "/storage/.kodi/addons/service.librespot/resources/lib/ls_addon.py", line 39, in get_settings
                                                       settings['name'] = settings['name'].format(socket.gethostname())
                                                   KeyError: 'kodi'
                                                   -->End of Python script error report<--
                                                   
2022-09-30 23:15:50.779 T:4543     INFO <general>: Python interpreter stopped
2022-09-30 23:16:50.835 T:1281    ERROR <general>: AddonVersion: 2.27.1 matrix.1 is not a valid version
```

**Host (what you are running `librespot` on):**
- OS: LibreELEC 19.4
- Platform: RPi 400

**Additional context**
Workaround from my end is changing line 39 of `.kodi/addons/service.librespot/resources/lib/ls_addon.py`:
from
`    settings['name'] = settings['name'].format(socket.gethostname())`
to
`    settings['name'] = socket.gethostname()`

I'm not sure what the underlying issue is or whether this workaround is even safe code at this point, but it seems to work for the moment.

**Comment by roderickvd** [comment]
You should report this upstream with Kodi.
`librespot` is not written in Python.

**Comment by shanemeagher** [comment]
As stated, this is a LibreELEC addon that packages librespot so post here:
https://forum.libreelec.tv/board/14-add-on-support/
