### ISSUE TITLE
Librespot  mDNS-related error on machine startup 

### ISSUE THREAD

**Issue by hamiltron** [librespot-org/librespot#1404]
### Description
Librespot appears to be throwing an mDNS-related error on machine startup when run as a systemd service. This doesn't kill the service, but leaves mDNS broken (so it's not visible in the Spotify app as a playback device). 

If I restart the service after startup there is no error, and if I add a 30 sec delay (using `ExecStartPre=/bin/sleep 30` in the service file), it also starts up without an issue. 

I'm wondering if there's another service dependency that needs to be added to the service file. Or is it possible to have librespot internally retry whatever failed? 

### Version
0.6.0 - built using `cargo install librespot`

### Host:
- OS: Ubuntu Server
- Platform: 2014 Mac Mini

### Systemd service file 
```
[Unit]
Description=Librespot (an open source Spotify client)
Documentation=https://github.com/librespot-org/librespot
Documentation=https://github.com/librespot-org/librespot/wiki/Options
Wants=network.target sound.target
After=network.target sound.target

[Service]
DynamicUser=yes
SupplementaryGroups=audio
Restart=always
RestartSec=10
ExecStart=/usr/bin/librespot --name "Living Room" --bitrate 320 --device-type speaker --volume-range 30

[Install]
WantedBy=multi-user.target
```

### Log
From `journalctl -u librespot.service`: 
```
Nov 24 20:54:11 spotifyconnect systemd[1]: Started librespot.service - Librespot (an open source Spotify client).
Nov 24 20:54:11 spotifyconnect librespot[804]: [2024-11-24T20:54:11Z INFO  librespot] librespot 0.6.0 VERGEN_IDEMPOTENT_OUTPUT (Built on 2024-11-24, Build ID: 6jiAyOYl, Profile: release)
Nov 24 20:54:11 spotifyconnect librespot[804]: [2024-11-24T20:54:11Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(30.0)
Nov 24 20:54:11 spotifyconnect librespot[804]: thread 'tokio-runtime-worker' panicked at /home/sconnect/.cargo/registry/src/index.crates.io-6f17d22bba15001f/librespot-discovery-0.6.0/src/lib.rs:4>
Nov 24 20:54:11 spotifyconnect librespot[804]: called `Result::unwrap()` on an `Err` value: DnsSdError(Os { code: 19, kind: Uncategorized, message: "No such device" })
Nov 24 20:54:11 spotifyconnect librespot[804]: stack backtrace:
Nov 24 20:54:11 spotifyconnect librespot[804]: [2024-11-24T20:54:11Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
Nov 24 20:54:11 spotifyconnect librespot[804]: [2024-11-24T20:54:11Z INFO  librespot_playback::audio_backend::rodio] Using Rodio sink with format S16 and cpal host: ALSA
Nov 24 20:54:11 spotifyconnect librespot[804]: [2024-11-24T20:54:11Z INFO  librespot_playback::audio_backend::rodio] Using audio device: default
Nov 24 20:54:11 spotifyconnect librespot[804]:    0:     0x595e7e2e7e3b - std::backtrace_rs::backtrace::libunwind::trace::he991e66e5f22a1db
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
Nov 24 20:54:11 spotifyconnect librespot[804]:    1:     0x595e7e2e7e3b - std::backtrace_rs::backtrace::trace_unsynchronized::h43f35a5576eecb13
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
Nov 24 20:54:11 spotifyconnect librespot[804]:    2:     0x595e7e2e7e3b - std::sys_common::backtrace::_print_fmt::hf9c799a68b2477fc
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:67:5
Nov 24 20:54:11 spotifyconnect librespot[804]:    3:     0x595e7e2e7e3b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2d48dfeb5948660
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:44:22
Nov 24 20:54:11 spotifyconnect librespot[804]:    4:     0x595e7e32cb70 - core::fmt::rt::Argument::fmt::h507ca91fbb1ef494
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/core/src/fmt/rt.rs:142:9
Nov 24 20:54:11 spotifyconnect librespot[804]:    5:     0x595e7e32cb70 - core::fmt::write::h4d5f6025aa566322
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/core/src/fmt/mod.rs:1120:17
Nov 24 20:54:11 spotifyconnect librespot[804]:    6:     0x595e7e2dafed - std::io::Write::write_fmt::hc088b3c8cc6dcb9f
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/io/mod.rs:1762:15
Nov 24 20:54:11 spotifyconnect librespot[804]:    7:     0x595e7e2e7c24 - std::sys_common::backtrace::_print::h231201f6cff8f56a
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:47:5
Nov 24 20:54:11 spotifyconnect librespot[804]:    8:     0x595e7e2e7c24 - std::sys_common::backtrace::print::h478d6be486f8cd2d
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:34:9
Nov 24 20:54:11 spotifyconnect librespot[804]:    9:     0x595e7e30fe1a - std::panicking::default_hook::{{closure}}::hf1c55106b4d45a90
Nov 24 20:54:11 spotifyconnect librespot[804]:   10:     0x595e7e30fabd - std::panicking::default_hook::h7b29000c631cc719
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:292:9
Nov 24 20:54:11 spotifyconnect librespot[804]:   11:     0x595e7e310238 - std::panicking::rust_panic_with_hook::h2a988919dd121561
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:779:13
Nov 24 20:54:11 spotifyconnect librespot[804]:   12:     0x595e7e2e821e - std::panicking::begin_panic_handler::{{closure}}::h3a9eaa1d23ecf555
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:657:13
Nov 24 20:54:11 spotifyconnect librespot[804]:   13:     0x595e7e2e8056 - std::sys_common::backtrace::__rust_end_short_backtrace::h813561fdec15f700
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:170:18
Nov 24 20:54:11 spotifyconnect librespot[804]:   14:     0x595e7e30ff62 - rust_begin_unwind
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:645:5
Nov 24 20:54:11 spotifyconnect librespot[804]:   15:     0x595e7d985785 - core::panicking::panic_fmt::hef0307862026e6f9
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:72:14
Nov 24 20:54:11 spotifyconnect librespot[804]:   16:     0x595e7d985f33 - core::result::unwrap_failed::h8393ef8d489acb45
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/core/src/result.rs:1653:5
Nov 24 20:54:11 spotifyconnect librespot[804]:   17:     0x595e7dac764c - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hb6ff2bf44a46c24f
Nov 24 20:54:11 spotifyconnect librespot[804]:   18:     0x595e7dab7296 - tokio::runtime::task::core::Core<T,S>::poll::h86bc5f204edfc32b
Nov 24 20:54:11 spotifyconnect librespot[804]:   19:     0x595e7dad05a7 - tokio::runtime::task::harness::Harness<T,S>::poll::he45923982f554afd
Nov 24 20:54:11 spotifyconnect librespot[804]:   20:     0x595e7e20017e - tokio::runtime::blocking::pool::Inner::run::h6bea6cc4f7efd364
Nov 24 20:54:11 spotifyconnect librespot[804]:   21:     0x595e7e1fb4d7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5318546ef6af7a8b
Nov 24 20:54:11 spotifyconnect librespot[804]:   22:     0x595e7e1fbfb9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1c791331d92e823d
Nov 24 20:54:11 spotifyconnect librespot[804]:   23:     0x595e7e2dd845 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hebd3f136d7c70a48
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/alloc/src/boxed.rs:2007:9
Nov 24 20:54:11 spotifyconnect librespot[804]:   24:     0x595e7e2dd845 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h813dea9db89ee3a5
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/alloc/src/boxed.rs:2007:9
Nov 24 20:54:11 spotifyconnect librespot[804]:   25:     0x595e7e2dd845 - std::sys::unix::thread::Thread::new::thread_start::h87ab7be5c1477cc7
Nov 24 20:54:11 spotifyconnect librespot[804]:                                at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys/unix/thread.rs:108:17
Nov 24 20:54:11 spotifyconnect librespot[804]:   26:     0x7ff22b09ca94 - <unknown>
Nov 24 20:54:11 spotifyconnect librespot[804]:   27:     0x7ff22b129c3c - <unknown>
Nov 24 20:54:11 spotifyconnect librespot[804]:   28:                0x0 - <unknown>
```

**Comment by wisp3rwind** [comment]
Just to be sure: This is `cargo install librespot` with default features?

**Comment by hamiltron** [comment]
As far as Io know, yes. I didn't addd any additional parameters to the command. (Sorry, I'm not familiar with the Rust toolchain.) When I'd run that command, it seemed to do a full compile every time. It failed a few times until I'd installed the pkg-config and libasound2-dev packages, then it succeeded. From there I had to copy the binary to `/usr/bin`. 

Also I forgot to mention the Ubuntu version is 24.04.

**Comment by wisp3rwind** [comment]
Ok, then this should be using the `libmdns` zeroconf backend.

This seems to be the same as https://github.com/librespot-org/libmdns/issues/50, i.e. some kind of network-not-yet-available issue. Someone would need to investigate what exactly is going on here... Similar to spotifyd, we might also implement a retry feature.

What kind of system are you running this on? If it has an MDNS responder running (e.g. Avahi on Linux), you could try building with one of the other zerconf backends, see also https://github.com/librespot-org/librespot/blob/dev/COMPILING.md#zeroconf-library-dependencies
For example
```sh
# Linux only, no additional dependencies, needs Avahi to be running
cargo build --features with-avahi librespot
```
or
```sh
# Should work on more systems, requires dns_sd to be available
cargo build --features with-dns-sd librespot
```

**Comment by yanorei32** [comment]
I have encountered the same issue.
If zeroconf retries are not implemented, shouldn't it exit with an appropriate error?
In the current implementation, it does not exit with an error, and therefore, the restart are not being triggered by Systemd.

**Comment by wisp3rwind** [comment]
The linked PR should cause librespot to exit due to this error.

That leaves the question open of where the actual issue is coming from, but that is already tracked in https://github.com/librespot-org/libmdns/issues/50.

**Comment by pejobo** [comment]
After a power outage today I experienced a problem that at least to me looks exactly like this issue:

```
-- Boot b158b82ed2584ebe8231daef6d609971 --
May 08 10:46:05 pi3 systemd[1]: Started Librespot (an open source Spotify client).
May 08 10:46:05 pi3 librespot[485]: [2025-05-08T08:46:05Z INFO  librespot] librespot 0.6.0 383a6f6 (Built on 2025-05-07, Build ID: fCUtZRBK, Profile: release
May 08 10:46:06 pi3 librespot[485]: [2025-05-08T08:46:06Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0)
May 08 10:46:06 pi3 librespot[485]: [2025-05-08T08:46:06Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
May 08 10:46:06 pi3 librespot[485]: [2025-05-08T08:46:06Z INFO  librespot_playback::audio_backend::alsa] Using AlsaSink with format: S16
May 08 10:46:06 pi3 librespot[485]: thread 'tokio-runtime-worker' panicked at discovery/src/lib.rs:408:14:
May 08 10:46:06 pi3 librespot[485]: called `Result::unwrap()` on an `Err` value: DnsSdError(Os { code: 19, kind: Uncategorized, message: "No such device" })
May 08 10:46:06 pi3 librespot[485]: stack backtrace:
May 08 10:46:06 pi3 librespot[485]:    0:   0xd35254 - std::backtrace_rs::backtrace::libunwind::trace::h12b352c498b75433
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
May 08 10:46:06 pi3 librespot[485]:    1:   0xd35254 - std::backtrace_rs::backtrace::trace_unsynchronized::h3af32b06e035abe7
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
May 08 10:46:06 pi3 librespot[485]:    2:   0xd35254 - std::sys_common::backtrace::_print_fmt::he2a3e2a40522362c
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
May 08 10:46:06 pi3 librespot[485]:    3:   0xd35254 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7c7da4e3f58c35a9
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
May 08 10:46:06 pi3 librespot[485]:    4:   0xd6799c - core::fmt::rt::Argument::fmt::h171b714554d3e2c0
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
May 08 10:46:06 pi3 librespot[485]:    5:   0xd6799c - core::fmt::write::h8eaf408dc91384a1
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
May 08 10:46:06 pi3 librespot[485]:    6:   0xd312d0 - std::io::Write::write_fmt::h5a545a5758e420d3
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
May 08 10:46:06 pi3 librespot[485]:    7:   0xd35068 - std::sys_common::backtrace::_print::hedb58f3b22cd053a
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
May 08 10:46:06 pi3 librespot[485]:    8:   0xd35068 - std::sys_common::backtrace::print::h8401c095f39b094d
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
May 08 10:46:06 pi3 librespot[485]:    9:   0xd36ce0 - std::panicking::default_hook::{{closure}}::ha0184dce5f3892e0
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:272:22
May 08 10:46:06 pi3 librespot[485]:   10:   0xd368b0 - std::panicking::default_hook::hbef41816fef2feb8
May 08 10:46:06 pi3 librespot[485]:                        at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
[...]
```

This is on ARM (Raspberry Pi), compiled yesterday from current main (`build librespot-cross cargo build --release --target arm-unknown-linux-gnueabihf --no-default-features --features "alsa-backend with-libmdns"`).

Is this worth a new ticket? Can anyone confirm that the changes here fixed the restart issue? 

For the time being I applied the `ExecStartPre=/bin/sleep 30` workaround..

**Comment by wisp3rwind** [comment]
> Is this worth a new ticket? Can anyone confirm that the changes here fixed the restart issue?
> 
> For the time being I applied the `ExecStartPre=/bin/sleep 30` workaround..

As already explained above: The error can still occur, see the libmdns issue. However, librespot should now exit in this case, instead of continuing to run in a degraded way.

**Comment by pejobo** [comment]
I got this, but I think I didn't bring my point across: It's was not exiting, that's why I had to apply the workaround (adding the sleep in the service file).

**Comment by wisp3rwind** [comment]
> I got this, but I think I didn't bring my point across: It's was not exiting, that's why I had to apply the workaround (adding the sleep in the service file).

You did get that point across. However, this should be fixed in the most recent development version of librespot (in fact, the line that the panic happens at in the traceback does not exist anymore in the source code). There hasn't been a release since then, so if you simply `cargo install`, you'll end up with an older version that doesn't have the fix yet.

**Comment by pejobo** [comment]
Ah, thank you. My fault.
