### ISSUE TITLE
thread 'main' panicked at 'calledResult::unwrap() with some accounts

### ISSUE THREAD

**Issue by flori4n** [librespot-org/librespot#175]
Hello,

I can't have access with a family account. I'm not sure if that something in your side or on spotify side.
I have a friend who's also premium and he's able to join and play my raspotify but I can't. (i can see it on my android but when I try the device it "pauses".
So it dosen't work with my account but it work with my friend account.
Any idea?

```
INFO:librespot_core::session: Country: "CH" thread 'main' panicked at 'calledResult::unwrap()on anErrvalue: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:860:4
note: Run withRUST_BACKTRACE=1for a backtrace. 
INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg 
INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-51qb.ap.spotify.com:4070" 
INFO:librespot_core::session: Authenticated as "xxxxxxxxxx" ! INFO:librespot::audio_backend::alsa: Using alsa sink 
INFO:librespot_core::session: Country: "CH" thread 'main' panicked at 'calledResult::unwrap()on anErrvalue: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:860:4 
note: Run withRUST_BACKTRACE=1for a backtrace. 
INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg
```

and my friend
```
INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2017-10-05. Build ID: POyxPQVg
INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-csw5.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "yyyyyyyyyyy" !
INFO:librespot::audio_backend::alsa: Using alsa sink
INFO:librespot_core::session: Country: "CH"
INFO:librespot::player: Loading track "Hocus Pocus"
INFO:librespot::player: Track "Hocus Pocus - Original Single Version" loaded

```

Thanks you

**Comment by sashahilton00** [comment]
Hi, as I mentioned a few days ago, spotify is rolling out updates gradually to all users, which contain a breaking change. This was fixed in commit 80e0bda. All you need to do is rebuild librespot and it'll be fixed.
