### ISSUE TITLE
Playback crashes with latest macOS Spotify client

### ISSUE THREAD

**Issue by thebigtouffe** [librespot-org/librespot#177]
Hello, 

I have upgraded Spotify client on macOS 10.12.6 and now use Spotify 1.0.75.483.g7ff4a0dc .
Spotify client is able to see my librespot server but when attempting to connect the server crashes. I used to have this problem with Android client, but after downgrading it was okay. The previous macOS client could connect fine to the server, so I suspect a change on Spotify's side.

Here is the traceback:

```
INFO:librespot: librespot 8971d3a (2017-10-05). Built on 2018-02-28. Build ID: VcXRStj5
INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-sxmn.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "XXXXXXXX" !
INFO:librespot::audio_backend::alsa: Using alsa sink
INFO:librespot_core::session: Country: "FR"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  11: <futures::stream::map::Map<S, F> as futures::stream::Stream>::poll
  12: <librespot::spirc::SpircTask as futures::future::Future>::poll
  13: <librespot::Main as futures::future::Future>::poll
  14: futures::task_impl::std::set
  15: <scoped_tls::ScopedKey<T>>::set
  16: tokio_core::reactor::Core::run
  17: librespot::main
  18: std::rt::lang_start::{{closure}}
  19: std::panicking::try::do_call
             at /checkout/src/libstd/rt.rs:59
             at /checkout/src/libstd/panicking.rs:480
  20: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  21: std::rt::lang_start_internal
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  22: main
  23: __libc_start_main
```

**Comment by ashthespy** [comment]
@thebigtouffe https://github.com/librespot-org/librespot/pull/167 fixes this.
Have you tried rebuilding?

**Comment by thebigtouffe** [comment]
Yes it works now, I ran the wrong binary, what a fool I made of myself, sorry. Thank you for replying so promptly!
