### ISSUE TITLE
librespot crashes when connecting from spotifyapp on android and ios

### ISSUE THREAD

**Issue by jerver** [librespot-org/librespot#181]
Hi, 1st of all thx for this beautiful software! 
Since yesterday, librespot is crashing when I use spotify connect on my ipad or android phone. From a windows 10 pc it is working well.  I have a raspotify installation on a rpi 3 with raspbian jessie lite. Hope someone can help me. Thx!

$ /usr/bin/librespot -n hello
INFO:librespot: librespot (raspotify) 4f3a594 (2018-02-17). Built on 2018-02-20. Build ID: 8u37iq02
INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-592p.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "spotify1967" !
INFO:librespot_playback::audio_backend::alsa: Using alsa sink
INFO:librespot_core::session: Country: "NL"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:916:5
stack backtrace:
   0:   0x8b5da3 - <unknown>
   1:   0x8bfefb - <unknown>
   2:   0x8ae45b - <unknown>
   3:   0x8adf37 - <unknown>
   4:   0x8ae907 - <unknown>
   5:   0x8ae74f - <unknown>
   6:   0x8ae6d7 - <unknown>
   7:   0x8ae67f - <unknown>
   8:   0x9170e3 - <unknown>
   9:   0x520bb3 - <unknown>
  10:   0x4f9d7f - <unknown>
  11:   0x518a8f - <unknown>
  12:   0x5037b3 - <unknown>
  13:   0x4acaff - <unknown>
  14:   0x49e3e3 - <unknown>
  15:   0x49775f - <unknown>
  16:   0x4ae403 - <unknown>
  17:   0x4979ab - <unknown>
  18:   0x8ae5af - <unknown>
  19:   0x8d527f - <unknown>
  20:   0x8b5a2f - <unknown>
  21:   0x4aee5f - main
  22: 0x76db2293 - __libc_start_main

**Comment by tomtaylor** [comment]
I believe this was fixed in https://github.com/librespot-org/librespot/pull/167

**Comment by sashahilton00** [comment]
This was indeed fixed in #167. The solution is to rebuild librespot with the latest commit. I assume you are using Raspotify from the fact that your binary is stripped, in which case, I believe v0.10.4 of raspotify has this fix included.

**Comment by herrwusel** [comment]
I can confirm this issue. Just did a fresh 'git clone' on a new system to cross compile. When I run librespot on my rpi3 I get the same error. Do you need any other information from me?

**Comment by sashahilton00** [comment]
We need a backtrace ideally. Where did you git clone from?

**Comment by herrwusel** [comment]
Backtrace:

> pi@music:~ $ RUST_BACKTRACE=1 librespot -n test
INFO:librespot: librespot 5f21c25 (2018-01-28). Built on 2018-01-30. Build ID: LkFdejze
WARN:mdns::fsm: error sending packet Error { repr: Os { code: 99, message: "Cannot assign requested address" } }
INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-h3rm.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "hrrwsl" !
INFO:librespot::audio_backend::alsa: Using alsa sink
INFO:librespot_core::session: Country: "DE"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: <futures::stream::map::Map<S, F> as futures::stream::Stream>::poll
  11: <librespot::spirc::SpircTask as futures::future::Future>::poll
  12: <futures::task_impl::Spawn<T>>::enter::{{closure}}
  13: librespot::main
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  15: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  16: __libc_start_main


> Where did you git clone from?

From here https://github.com/librespot-org/librespot

**Comment by sashahilton00** [comment]
The reason that yours isn't working is because it is an older version, pre #167 fix, for anyone else who comes across this issue.
