### ISSUE TITLE
Crash in the middle of playback (ChannelError)

### ISSUE THREAD

**Issue by l3d00m** [librespot-org/librespot#183]
*Edited the issue as it just happened again and I was able to offer a more detailed description*

This crash happened in the middle of playback without any kind of input from my side, playback just stopped. The interesting thing here is that the `raspotify` service / librespot did not terminate immediately, but rather as soon as I clicked play in the client again. This finally crashed librespot with a `SendError` (Notice: This log is **not** truncated between the two errors)

Debug info: `librespot (raspotify) 593dfa0 (2018-02-27). Built on 2018-03-01. Build ID: tKkd5pOH`

```
Mar 06 16:41:13 raspberrypi librespot[25865]: INFO:librespot_playback::player: Loading track "In the Sunshine - Lion Boy Electrify Remix"
Mar 06 16:41:18 raspberrypi librespot[25865]: ERROR:librespot_core::channel: channel error: 2 1
Mar 06 16:41:18 raspberrypi librespot[25865]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ChannelError', /checkout/src/libcore/result.rs:916:5
Mar 06 16:41:18 raspberrypi librespot[25865]: stack backtrace:
Mar 06 16:41:18 raspberrypi librespot[25865]:    0:   0x86b057 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hb6166e15fda1e065
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Mar 06 16:41:18 raspberrypi librespot[25865]:    1:   0x8752bb - std::sys_common::backtrace::print::hbb547a48d4d45c54
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/sys_common/backtrace.rs:68
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/sys_common/backtrace.rs:57
Mar 06 16:41:18 raspberrypi librespot[25865]:    2:   0x8638d7 - std::panicking::default_hook::{{closure}}::hb3351df37d61d489
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:381
Mar 06 16:41:18 raspberrypi librespot[25865]:    3:   0x8633b3 - std::panicking::default_hook::ha118e44019160a5b
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:397
Mar 06 16:41:18 raspberrypi librespot[25865]:    4:   0x863d83 - std::panicking::rust_panic_with_hook::h9cedc3dcc869a838
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:577
Mar 06 16:41:18 raspberrypi librespot[25865]:    5:   0x863bcb - std::panicking::begin_panic::h8259fca926742a49
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:538
Mar 06 16:41:18 raspberrypi librespot[25865]:    6:   0x863b53 - std::panicking::begin_panic_fmt::hb044a1e2dca6dd17
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:522
Mar 06 16:41:18 raspberrypi librespot[25865]:    7:   0x863afb - rust_begin_unwind
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:498
Mar 06 16:41:18 raspberrypi librespot[25865]:    8:   0x8ccbcf - core::panicking::panic_fmt::hd4212c5d5ed3b640
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libcore/panicking.rs:71
Mar 06 16:41:18 raspberrypi librespot[25865]:    9:   0x532b5b - core::result::unwrap_failed::h42b2604478a50540
Mar 06 16:41:18 raspberrypi librespot[25865]:   10:   0x52f3a3 - librespot_playback::player::PlayerInternal::run::h70351a6b852f9e84
Mar 06 16:41:18 raspberrypi librespot[25865]:   11:   0x44642f - std::sys_common::backtrace::__rust_begin_short_backtrace::hf6ae4f7de65ea8a7
Mar 06 16:41:18 raspberrypi librespot[25865]:   12:   0x444a07 - std::panicking::try::do_call::h85d267ef377c0798
Mar 06 16:41:18 raspberrypi librespot[25865]:   13:   0x88a65b - __rust_maybe_catch_panic
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libpanic_unwind/lib.rs:101
Mar 06 16:41:18 raspberrypi librespot[25865]:   14:   0x467b8f - <F as alloc::boxed::FnBox<A>>::call_box::h214eae47b542181b
Mar 06 16:41:18 raspberrypi librespot[25865]:   15:   0x8719cf - std::sys_common::thread::start_thread::h5c8ded4a8e2b80a7
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/liballoc/boxed.rs:825
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/sys_common/thread.rs:24
Mar 06 16:41:18 raspberrypi librespot[25865]:   16:   0x8643df - std::sys::unix::thread::Thread::new::thread_start::h38f4e2017be83d0f
Mar 06 16:41:18 raspberrypi librespot[25865]:                        at /checkout/src/libstd/sys/unix/thread.rs:90
Mar 06 17:14:10 raspberrypi librespot[25865]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /checkout/src/libcore/result.rs:916:5
Mar 06 17:14:10 raspberrypi librespot[25865]: stack backtrace:
Mar 06 17:14:10 raspberrypi librespot[25865]:    0:   0x86b057 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hb6166e15fda1e065
Mar 06 17:14:10 raspberrypi librespot[25865]:                        at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Mar 06 17:14:10 raspberrypi librespot[25865]:    1:   0x8752bb - std::sys_common::backtrace::print::hbb547a48d4d45c54
Mar 06 17:14:10 raspberrypi librespot[25865]:                        at /checkout/src/libstd/sys_common/backtrace.rs:68
Mar 06 17:14:10 raspberrypi librespot[25865]:                        at /checkout/src/libstd/sys_common/backtrace.rs:57
Mar 06 17:14:10 raspberrypi librespot[25865]:    2:   0x8638d7 - std::panicking::default_hook::{{closure}}::hb3351df37d61d489
Mar 06 17:14:10 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:381
Mar 06 17:14:10 raspberrypi librespot[25865]:    3:   0x8633b3 - std::panicking::default_hook::ha118e44019160a5b
Mar 06 17:14:10 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:397
Mar 06 17:14:10 raspberrypi librespot[25865]:    4:   0x863d83 - std::panicking::rust_panic_with_hook::h9cedc3dcc869a838
Mar 06 17:14:10 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:577
Mar 06 17:14:10 raspberrypi librespot[25865]:    5:   0x863bcb - std::panicking::begin_panic::h8259fca926742a49
Mar 06 17:14:10 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:538
Mar 06 17:14:10 raspberrypi librespot[25865]:    6:   0x863b53 - std::panicking::begin_panic_fmt::hb044a1e2dca6dd17
Mar 06 17:14:10 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:522
Mar 06 17:14:10 raspberrypi librespot[25865]:    7:   0x863afb - rust_begin_unwind
Mar 06 17:14:10 raspberrypi librespot[25865]:                        at /checkout/src/libstd/panicking.rs:498
Mar 06 17:14:10 raspberrypi systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a

```

**Comment by sashahilton00** [comment]
I'm not actually sure what is causing this, as the backtrace doesn't say much. Anyone care to weigh in with any thoughts?

**Comment by ComlOnline** [comment]
I'm thinking its something like #172 where there error doesn't cause a panic, until something else fails. I cant see anywhere to point a finger though.

**Comment by sylbarth** [comment]
Hi,

Having the same problem after a few songs.

May 22 21:01:02 DietPi librespot[1353]: ERROR:librespot_core::channel: channel error: 2 1 May 22 21:01:02 DietPi librespot[1353]: WARN:librespot_audio::fetch: error from channel May 22 21:01:54 DietPi librespot[1353]: WARN:mdns::fsm: dropping truncated packet from V4(192.168.1.1:5353)
and only a "systemctl status raspotify" correct the problem.`

But as far as I remember, it used to work perfectly in the past, and do not remember doing any update/upgrade.

So, maybe a change on the Spotify side?

**Comment by l3d00m** [comment]
It usually crashes if you try to play the next song, this avoids having to log in via ssh @sylbarth

**Comment by sylbarth** [comment]
I will try, thanks

**Comment by ComlOnline** [comment]
@l3d00m your comment from #215 seems to indicate that this is resolved (in that it no longer happens, not that we know what caused it.) would you say that is the case for this as well?

**Comment by l3d00m** [comment]
I could just reopen if it should occur again, librespot was pretty stable in the last days

**Comment by ComlOnline** [comment]
That's good to hear, in that case that may be easiest.

**Comment by l3d00m** [comment]
It did happen again yesterday for me, that was quick. Same error as above. This seems to be the most frequent crash for me (I'm using librespot nearly 12 hours a day)

**Comment by 1337sup3rh4x0r** [comment]
Hi there,
I am seeing the same bahaviour for a specific track ("spotify:track:6W2i0WRMkwj5IY4g2PAc3M"). Every time I try to play it, librespot crashes reproducibly with the same SendError I see in @l3d00m's report:

	2018-12-07 08-22-39 [Info] (Spotify) INFO:librespot_playback::player: Loading track "In Flames" with Spotify URI "spotify:track:6W2i0WRMkwj5IY4g2PAc3M"
	2018-12-07 08-22-40 [Info] (Spotify) ERROR:librespot_core::channel: channel error: 2 1                                              
	2018-12-07 08-22-40 [Info] (Spotify) thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ChannelError', src/libcore/result.rs:916:5
	2018-12-07 08-22-40 [Info] stack backtrace:                                                                                         
	2018-12-07 08-22-40 [Info] (Spotify) 0:          0x151676b - std::sys::                                                             
	2018-12-07 08-22-40 [Info] (Spotify) unix::backtrace::tracing::imp::unwind_backtrace::h8a68556765699628                             
	2018-12-07 08-22-40 [Info]    1:          0x151d5be - std::sys_common::backtrace::print::hd9cd2cd1216dc9cb                          
	2018-12-07 08-22-40 [Info]    2:          0x1515f40 - std::panicking::default_hook::{{closure}}::h1c4745b6dc9ac2fd                  
	2018-12-07 08-22-40 [Info]    3:          0x1515c81 - std::panicking::default_hook::                                                
	2018-12-07 08-22-40 [Info] (Spotify) h343503bbea399679                                                                              
	2018-12-07 08-22-40 [Info] (Spotify) 4:          0x1516377 - std::panicking::rust_panic_with_hook::hcf6685586ca984c2                
	2018-12-07 08-22-40 [Info]    5:                                                                                                    
	2018-12-07 08-22-40 [Info] (Spotify) 0x15161ce - std::panicking::begin_panic::h1cc35849ea44407b                                     
	2018-12-07 08-22-40 [Info]    6:          0x151613a - std::panicking::begin_panic_fmt::hf9347143b9897b85                            
	2018-12-07 08-22-40 [Info]    7:                                                                                                    
	2018-12-07 08-22-40 [Info] (Spotify) 0x15160d2 - rust_begin_unwind                                                                  
	2018-12-07 08-22-40 [Info]    8:          0x15687f0 - core::panicking::panic_fmt::hb9c0f300e4a5aca2                                 
	2018-12-07 08-22-40 [Info]    9:          0x11854fb - core::result::unwrap_failed::h2017edddc8677dbd                                
	2018-12-07 08-22-40 [Info]   10:                                                                                                    
	2018-12-07 08-22-40 [Info] (Spotify) 0x11aa56e - librespot_playback::player::PlayerInternal::run::he04ad27f85c92378                 
	2018-12-07 08-22-40 [Info]   11:          0x10a757e - std::sys_common::backtrace::__rust_begin_short_backtrace::h76841afb6f2fb021   
	2018-12-07 08-22-40 [Info]   12:          0x10b3ac7 - std::panicking::try::do_call::h829bbef80e711efb                               
	2018-12-07 08-22-40 [Info]   13:          0x1535cfe - __rust_maybe_catch_panic                                                      
	2018-12-07 08-22-40 [Info] (Spotify) at src/libpanic_unwind/lib.rs:101                                                              
	2018-12-07 08-22-40 [Info]   14:          0x10c4eca - <F as alloc::boxed::FnBox<A                                                   
	2018-12-07 08-22-40 [Info] (Spotify) >>::call_box::h31aa12e7dc0f48fc                                                                
	2018-12-07 08-22-40 [Info]   15:          0x151fe87 - std::sys_common::thread::start_thread::h0da9fba7855cc95d                      
	2018-12-07 08-22-40 [Info]   16:          0x1524128 -                                                                               
	2018-12-07 08-22-40 [Info] (Spotify) std::sys::unix::thread::Thread::new::thread_start::hdb3b5b83d332bdef                           
	2018-12-07 08-22-40 [Info]   17:        0x802022854 - pthread_create                                                                
	2018-12-07 08-22-40 [Info]   18:                0x0 - <unknown>         
	2018-12-07 08-23-22 [Info] (Spotify) thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:916:5
	2018-12-07 08-23-22 [Info] (Spotify) stack backtrace:                                                                               
	2018-12-07 08-23-22 [Info]    0:          0x151676b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h8a68556765699628  
	2018-12-07 08-23-22 [Info]    1:          0x151d5be - std::sys_common::backtrace::print::hd9cd2cd1216dc9cb                          
	2018-12-07 08-23-22 [Info]    2:          0x1515f40 - std::panicking::default_hook::{{closure}}::h1c4745b6dc9ac2fd                  
	2018-12-07 08-23-22 [Info]    3:          0x1515c81 - std                                                                           
	2018-12-07 08-23-22 [Info] (Spotify) ::panicking::default_hook::h343503bbea399679                                                   
	2018-12-07 08-23-22 [Info]    4:          0x1516377 - std::panicking::rust_panic_with_hook::hcf6685586ca984c2                       
	2018-12-07 08-23-22 [Info]    5:          0x15161ce - std::panicking::begin_panic::h1cc35849ea44407b                                
	2018-12-07 08-23-22 [Info]    6:          0x151613a - std::panicking::begin_panic_fmt::hf9347143b9897b85                            
	2018-12-07 08-23-22 [Info]    7:          0x15160d2 - rust_begin_unwind                                                             
	2018-12-07 08-23-22 [Info]    8:          0x15687f0 - core::panicking::panic_fmt::hb9c0f300e4a5aca2                                 
	2018-12-07 08-23-22 [Info]    9:          0x118591d                                                                                 
	2018-12-07 08-23-22 [Info] (Spotify) - core::result::unwrap_failed::hb4771ff019324ed1                                               
	2018-12-07 08-23-22 [Info]   10:          0x11a65bb - librespot_playback::player::Player::load::h85c99afb22013536                   
	2018-12-07 08-23-22 [Info]   11:          0x1141dba - librespot_connect::spirc::SpircTask::load_track::ha46f6ae153768fac            
	2018-12-07 08-23-22 [Info]   12:          0x1141036 - librespot_connect::spirc::SpircTask::handle_next::h5e284a6fa695cd3f           
	2018-12-07 08-23-22 [Info]   13:          0x1140298 - <librespot_connect::spirc::SpircTask as futures::future::Future>::poll::h0ee40dc90b15a1f7
	2018-12-07 08-23-22 [Info]   14:                                                                                                    
	2018-12-07 08-23-22 [Info] (Spotify) 0x10bd816 - <librespot::Main as futures::future::Future>::poll::hae12f1c7dff3167b              
	2018-12-07 08-23-22 [Info]   15:          0x10aee97 - futures::task_impl::std::set::h0f2daaea18001f19                               
	2018-12-07 08-23-22 [Info]   16:          0x10b83b3 - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::hed49175c287490a4
	2018-12-07 08-23-22 [Info]   17:          0x10aefb7 - futures::task_impl::std::set::h7a6fed570cb7a5d6                               
	2018-12-07 08-23-22 [Info]   18:          0x10c32d2 - <std::thread::local::LocalKey<T>>::with::h2916a1b9bf04867d                    
	2018-12-07 08-23-22 [Info]   19:          0x10c3d4b - <std::thread::local::LocalKey<T>>::with::h813a129ed3d8d4ee                    
	2018-12-07 08-23-22 [Info]   20:          0x10c3f15 - <std::thread::local::LocalKey<T>>::with                                       
	2018-12-07 08-23-22 [Info] (Spotify) ::hade78218634eee7d                                                                            
	2018-12-07 08-23-22 [Info]   21:          0x10a6381 - tokio_core::reactor::Core::run::hc06fcfa374aeaabd                             
	2018-12-07 08-23-22 [Info]   22:          0x10be9da - librespot::main::h728df9bb283def3d                                            
	2018-12-07 08-23-22 [Info]   23:          0x10a7605 - std::rt::lang_start::{{closure}}::hcb91eb1e5e820223                           
	2018-12-07 08-23-22 [Info]   24:          0x1516047 - std::panicking::try::do_call::hde3e6eab4ea20b2a                               
	2018-12-07 08-23-22 [Info]   25:          0x1535cfe - __rust_maybe_catch_panic                                                      
	2018-12-07 08-23-22 [Info]                                at src/libpanic_unwind/lib.rs:101                                         
	2018-12-07 08-23-22 [Info]   26:          0x1516557 - std::rt::lang_start_internal::hf081483bf15700db                               
	2018-12-07 08-23-22 [Info]   27:          0x10bed1b - main                                                                          
	2018-12-07 08-23-22 [Info]   28:          0x10a0be0 - _start                                                                        
	2018-12-07 08-23-22 [Info]   29:        0x8019defff - <unknown>                                                                     
	2018-12-07 08-23-22 [Info] (Spotify) ERROR:librespot_playback::player: Player thread panicked!                                      
	2018-12-07 08-23-22 [Err] (PipeStream) Exception: end of file

**Comment by torbatschow** [comment]
Same here:
```
INFO:librespot_playback::player: Loading track "Blue Monk" with Spotify URI "spotify:track:7fPNGpYUUOEdWI2YNeBk9a"
ERROR:librespot_core::channel: channel error: 2 1
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ChannelError', libcore/result.rs:916:5
stack backtrace:
   0:   0x9480a7 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h30ee2f9fcceb7741
   1:   0x952177 - std::sys_common::backtrace::print::h188b4530fc939445
   2:   0x940c7b - std::panicking::default_hook::{{closure}}::hea20e4e5428f90f2
   3:   0x94075f - std::panicking::default_hook::h0562ad1b2909b8a0
   4:   0x94113f - std::panicking::rust_panic_with_hook::he6693bd018612b1b
   5:   0x940f7f - std::panicking::begin_panic::h1d6f8876eba07524
   6:   0x940ef7 - std::panicking::begin_panic_fmt::h3c0bf37bbb2114d9
   7:   0x940e9f - rust_begin_unwind
   8:   0x9739f7 - core::panicking::panic_fmt::hd86eed07deb71f24
   9:   0x571b27 - core::result::unwrap_failed::h3ab73819092ccdb3
  10:   0x5a53f7 - librespot_playback::player::PlayerInternal::run::h1a06063b5195ea22
  11:   0x48bf67 - std::sys_common::backtrace::__rust_begin_short_backtrace::h08ffc4d09de60386
  12:   0x4a6503 - std::panicking::try::do_call::h0e05f893c7368382
  13:   0x968653 - __rust_maybe_catch_panic
  14:   0x4a7a8f - <F as alloc::boxed::FnBox<A>>::call_box::hcfbfbee7da2f26a7
  15:   0x94ed1f - std::sys_common::thread::start_thread::h89a10d580fc48a13
  16:   0x9417ab - std::sys::unix::thread::Thread::new::thread_start::h540c8b96c4d30f84
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', libcore/result.rs:916:5
stack backtrace:
   0:   0x9480a7 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h30ee2f9fcceb7741
   1:   0x952177 - std::sys_common::backtrace::print::h188b4530fc939445
   2:   0x940c7b - std::panicking::default_hook::{{closure}}::hea20e4e5428f90f2
   3:   0x94075f - std::panicking::default_hook::h0562ad1b2909b8a0
   4:   0x94113f - std::panicking::rust_panic_with_hook::he6693bd018612b1b
   5:   0x940f7f - std::panicking::begin_panic::h1d6f8876eba07524
   6:   0x940ef7 - std::panicking::begin_panic_fmt::h3c0bf37bbb2114d9
   7:   0x940e9f - rust_begin_unwind
   8:   0x9739f7 - core::panicking::panic_fmt::hd86eed07deb71f24
   9:   0x571ce3 - core::result::unwrap_failed::h58209406d91b6cfc
  10:   0x59cfaf - librespot_playback::player::Player::seek::h93926af333bf269e
  11:   0x52bd5f - <librespot_connect::spirc::SpircTask as futures::future::Future>::poll::h6fad2fa0059f4769
  12:   0x49f353 - <librespot::Main as futures::future::Future>::poll::h539d81d0d7fc604e
  13:   0x497923 - <futures::task_impl::Spawn<T>>::poll_future_notify::hc793e63d1c0e40bd
  14:   0x497533 - <futures::task_impl::Spawn<T>>::poll_future_notify::h316b75fc95b60e57
  15:   0x4a9baf - <std::thread::local::LocalKey<T>>::with::h1aa0d59321151dc6
  16:   0x4a8353 - <tokio::executor::current_thread::Entered<'a, P>>::block_on::h21cccd449b5bfba6
  17:   0x4a9da7 - <std::thread::local::LocalKey<T>>::with::hcb2d13dda826cab1
  18:   0x4aa1eb - <std::thread::local::LocalKey<T>>::with::he25b5d5b77d5c83d
  19:   0x4aa03b - <std::thread::local::LocalKey<T>>::with::hd6c05258022b02b2
  20:   0x48bcdb - <scoped_tls::ScopedKey<T>>::set::h6ee6d8dc724b4fca
  21:   0x4ad0b7 - tokio_core::reactor::Core::run::hcce9a4bdc1b13d60
  22:   0x4a1653 - librespot::main::h660086c8b6a49ff8
  23:   0x48bff3 - std::rt::lang_start::{{closure}}::h532f1c9b25462a64
  24:   0x940dcf - std::panicking::try::do_call::h002a10acc5f16bb3
  25:   0x968653 - __rust_maybe_catch_panic
  26:   0x947ca7 - std::rt::lang_start_internal::he9d59cee8e8b1fd5
  27:   0x4a2197 - main
  28: 0x76c6f677 - __libc_start_main
ERROR:librespot_playback::player: Player thread panicked!
```

**Comment by zkiiito** [comment]
happens about hourly on my rpi :(

**Comment by 1337sup3rh4x0r** [comment]
I think @kingosticks pointed towards what is going wrong here in #280.

The way I understand it, is that spotify is slowly starting to serve more and more songs via some content delivery network and no longer directly via their initial servers. Librespot is not able to handle this different song source (yet).

**Comment by roderickvd** [comment]
Was fixed upstream on Spotify's end.
