### ISSUE TITLE
librespot crash on specific songs

### ISSUE THREAD

**Issue by flori4n** [librespot-org/librespot#234]
Hello all

Each time I start to listen this song it crash: Tubbe - In Berlin
[link to the Song](https://open.spotify.com/track/5aMzdlgZnDYa08Man9gm8E?si=FJ2aJ8W-RPqG5v_eLk8d8Q)
I'm using docker on a RPI with this [Dockerfile](https://gitlab.com/girard.florian/spotify)
```Python
thread 'main' panicked at 'assertion failed: new_index < self.shared.chunk_count', audio/src/fetch.rs:232:9,
INFO:librespot_playback::player: Loading track "In Berlin" with Spotify URI "spotify:track:5aMzdlgZnDYa08Man9gm8E",
stack backtrace:,
  11:   0x90a40f - <scoped_tls::ScopedKey<T>>::set::he0659ca76ab7b331,
   3:   0x9e5f77 - std::panicking::default_hook::h637e82b93eb77513,
   0:   0x9efd1b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hd7376efaf737a6cb,
   1:   0x9f6d63 - std::sys_common::backtrace::print::h0b8b4ef073b17e82,
                       at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49,
                       at libstd/sys_common/backtrace.rs:71,
                       at libstd/sys_common/backtrace.rs:59,
   2:   0x9e6323 - std::panicking::default_hook::{{closure}}::h984bb18536e1dcf9,
                       at libstd/panicking.rs:207,
   4:   0x9e67cb - std::panicking::rust_panic_with_hook::h4c1dc13cc6e725f4,
                       at libstd/panicking.rs:402,
                       at libstd/panicking.rs:223,
   7:   0x5debe7 - <librespot_audio::fetch::AudioFileFetch as futures::future::Future>::poll::hd8c8d35ba13b593a,
   6:   0x5dea9f - librespot_audio::fetch::AudioFileFetch::download::h226e13f62ab0b42c,
   5:   0x5e042b - std::panicking::begin_panic::h4cf1c8cda6c092b9,
  10:   0x914347 - <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick::h3b2f9eaab1a83b5f,
   8:   0x91afeb - <futures::task_impl::Spawn<T>>::poll_future_notify::hed62a615534d92ce,
   9:   0x91565f - <std::thread::local::LocalKey<T>>::with::h0d46b62ebb7297c4,
  19:   0x9e6477 - std::panicking::try::do_call::h803676a6686fa35a,
  18:   0x524cc3 - std::rt::lang_start::{{closure}}::h56d13da8f0c00177,
  17:   0x5317d3 - librespot::main::h583a074fae9ff638,
  16:   0x50e8ef - tokio_core::reactor::Core::run::h43a6a16fa99f0069,
  14:   0x9162bb - <std::thread::local::LocalKey<T>>::with::hb2e6cf69cbee52a1,
  13:   0x91643b - <std::thread::local::LocalKey<T>>::with::hd873a3d9feee8a6f,
  12:   0x915cd3 - <std::thread::local::LocalKey<T>>::with::hb116f9b6a776bfb1,
  15:   0x90ffc7 - tokio_core::reactor::Core::poll::h22adb55544452147,
                       at libstd/rt.rs:59,
                       at libstd/panicking.rs:306,
  20:   0x9fd943 - __rust_maybe_catch_panic,
                       at libpanic_unwind/lib.rs:102,
  21:   0x9e390f - std::rt::lang_start_internal::h8d13ab8f0c59613e,
                       at libstd/panic.rs:361,
                       at libstd/panicking.rs:285,
                       at libstd/rt.rs:58,
  22:   0x532223 - main,
  23: 0x76d31293 - __libc_start_main
```

thanks you
Flo

**Comment by ashthespy** [comment]
Never saw this issue before opening mine - Cross ref #234

**Comment by sashahilton00** [comment]
#250 has a patch that we should implement to fix this. in the meantime, closing this issue, please track in #250.
