### ISSUE TITLE
Completely stopped working today

### ISSUE THREAD

**Issue by michaelherger** [librespot-org/librespot#272]
Some of my users reported that spotty/librespot stopped working today. And indeed I can no longer play anything using librespot. Here's  an example stack trace:

```
INFO:librespot: librespot c211511 (2018-11-19). Built on 2018-12-01. Build ID: FlEpfdFB
WARN:mdns: Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }
INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-cxq4.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "xxxxxxx" !
INFO:librespot_core::session: Country: "CH"
INFO:librespot_playback::player: Loading track "It's All Over Now - Live" with Spotify URI "spotify:track:2rFoyoRGNu5XiHngfVLpKL"
ERROR:librespot_core::channel: channel error: 2 1
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ChannelError', libcore/result.rs:1009:5
stack backtrace:
   0:        0x1091600df - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hd303b0cd45bccf60
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:        0x10914b69d - std::sys_common::backtrace::print::hf2fe31942821bdcb
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:        0x109162ea3 - std::panicking::default_hook::{{closure}}::h748cb38cc840cba6
                               at libstd/panicking.rs:211
   3:        0x109162c2c - std::panicking::default_hook::h81d2ef89c2ad110e
                               at libstd/panicking.rs:227
   4:        0x1091635d7 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::hc265418ddf96c674
                               at libstd/panicking.rs:477
   5:        0x10916313c - std::panicking::continue_panic_fmt::h2d9dbf1e069d262d
                               at libstd/panicking.rs:391
   6:        0x109163028 - std::panicking::try::do_call::hcfe6ac53944e0624
                               at libstd/panicking.rs:326
   7:        0x1091a7f71 - core::ptr::drop_in_place::h2136aea44990720c
                               at libcore/panicking.rs:77
   8:        0x1085bf5e1 - core::char::methods::<impl char>::len_utf8::h74bd7d39878f2997
                               at libcore/macros.rs:26
   9:        0x1085be707 - core::char::methods::<impl char>::len_utf8::h74bd7d39878f2997
                               at libcore/result.rs:808
  10:        0x1085d8fb8 - librespot_playback::player::PlayerInternal::load_track::he909ca43b98c52dd
                               at playback/src/player.rs:567
  11:        0x1085d6fee - librespot_playback::player::PlayerInternal::handle_command::h735a15e843b94450
                               at playback/src/player.rs:405
  12:        0x1085d5c66 - librespot_playback::player::PlayerState::playing_to_paused::h86b2748f1dfa36c2
                               at playback/src/player.rs:318
  13:        0x1084d86e9 - librespot_playback::player::Player::new::{{closure}}::h95dd6495da5ef102
                               at /Users/mh/Dropbox/Squeezebox/git/librespot/playback/src/player.rs:139
  14:        0x1085020a5 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfc3b23d20a425bdf
                               at libstd/sys_common/backtrace.rs:136
  15:        0x1084ec625 - std::thread::Builder::spawn::{{closure}}::{{closure}}::h1406ade678026ab3
                               at libstd/thread/mod.rs:409
  16:        0x1084f729b - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hbaa3901d2c5bb382
                               at libstd/panic.rs:313
  17:        0x1084efc91 - std::panicking::try::do_call::hd83b64a0c2c44508
                               at libstd/panicking.rs:310
  18:        0x109170cce - macho_symbol_search
                               at libpanic_unwind/lib.rs:103
  19:        0x1084efb73 - std::panicking::try::hdfcb7456ff8a8fd8
                               at libstd/panicking.rs:289
  20:        0x1084f72e5 - std::panic::catch_unwind::h03c6725723da564f
                               at libstd/panic.rs:392
  21:        0x1084ec466 - std::thread::Builder::spawn::{{closure}}::h0f1cf98566747bb2
                               at libstd/thread/mod.rs:408
  22:        0x1084ec66a - <F as alloc::boxed::FnBox<A>>::call_box::hf7f60fe97920079d
                               at liballoc/boxed.rs:646
  23:        0x109162567 - std::sys_common::thread::start_thread::ha68f94e048f96d59
                               at liballoc/boxed.rs:656
                               at libstd/sys_common/thread.rs:24
  24:        0x10914a6b8 - std::sys::unix::thread::Thread::new::thread_start::h57baa5b47ae41e12
                               at libstd/sys/unix/thread.rs:90
  25:     0x7fff698b3338 - _pthread_body
  26:     0x7fff698b62a6 - _pthread_start
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', libcore/result.rs:1009:5
stack backtrace:
   0:        0x1091600df - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hd303b0cd45bccf60
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:        0x10914b69d - std::sys_common::backtrace::print::hf2fe31942821bdcb
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:        0x109162ea3 - std::panicking::default_hook::{{closure}}::h748cb38cc840cba6
                               at libstd/panicking.rs:211
   3:        0x109162c2c - std::panicking::default_hook::h81d2ef89c2ad110e
                               at libstd/panicking.rs:227
   4:        0x1091635d7 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::hc265418ddf96c674
                               at libstd/panicking.rs:477
   5:        0x10916313c - std::panicking::continue_panic_fmt::h2d9dbf1e069d262d
                               at libstd/panicking.rs:391
   6:        0x109163028 - std::panicking::try::do_call::hcfe6ac53944e0624
                               at libstd/panicking.rs:326
   7:        0x1091a7f71 - core::ptr::drop_in_place::h2136aea44990720c
                               at libcore/panicking.rs:77
   8:        0x1085bf86d - core::char::methods::<impl char>::len_utf8::h74bd7d39878f2997
                               at libcore/macros.rs:26
   9:        0x1085bde34 - core::char::methods::<impl char>::len_utf8::h74bd7d39878f2997
                               at libcore/result.rs:808
  10:        0x1085d4716 - librespot_playback::player::Player::command::h2bd47c42cc28262f
                               at playback/src/player.rs:152
  11:        0x1085d484c - librespot_playback::player::Player::command::h2bd47c42cc28262f
                               at playback/src/player.rs:168
  12:        0x10855ea55 - librespot_connect::spirc::SpircTask::handle_play::h0d605061aff70d3d
                               at connect/src/spirc.rs:557
  13:        0x10855de7a - librespot_connect::spirc::SpircTask::handle_frame::h10b800b38367f3c8
                               at connect/src/spirc.rs:464
  14:        0x10855cf39 - librespot_connect::spirc::volume_to_mixer::hc7436388ca271024
                               at connect/src/spirc.rs:314
  15:        0x108506393 - <librespot::Main as futures::future::Future>::poll::hd36ce322039c5d9e
                               at src/main.rs:458
  16:        0x1084df7c4 - <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::h82f7365572be9cd6
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  17:        0x1084dfb2f - <futures::task_impl::Spawn<T>>::enter::{{closure}}::he28862100908ab10
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  18:        0x1084f9b06 - futures::task_impl::std::set::he31f47467fa961e7
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/std/mod.rs:78
  19:        0x1084dfaa7 - <futures::task_impl::Spawn<T>>::enter::hb377948945542b7f
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  20:        0x1084df741 - <futures::task_impl::Spawn<T>>::poll_future_notify::h031fd01f30d2d85d
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  21:        0x1084f7c33 - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h5cb39b46ff9dab00
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:236
  22:        0x1084e8ff2 - <futures::future::lazy::Lazy<F, R>>::get::h2435701958a507b3
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/lazy.rs:64
  23:        0x1084e9134 - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::hd5b77e11ffc73f50
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/lazy.rs:82
  24:        0x1084df7f4 - <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::hc41f743bf4c27280
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  25:        0x1084dfaff - <futures::task_impl::Spawn<T>>::enter::{{closure}}::hd18369a653f37560
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  26:        0x1084f99e6 - futures::task_impl::std::set::h4168f9c470ec7d5d
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/std/mod.rs:78
  27:        0x1084df987 - <futures::task_impl::Spawn<T>>::enter::h4b5b5c351af72383
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  28:        0x1084df7a1 - <futures::task_impl::Spawn<T>>::poll_future_notify::hed63c0e7ef199ff1
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  29:        0x1084df4a0 - <tokio::executor::current_thread::Entered<'a, P>>::block_on::{{closure}}::h7e9547329812f14c
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:445
  30:        0x1084df13c - <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}::{{closure}}::hb05597afb99d02ff
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:657
  31:        0x1084df027 - tokio::executor::current_thread::CurrentRunner::set_spawn::hf120994948bcb018
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:689
  32:        0x1084df10a - <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}::h4d6e71facdd89849
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:656
  33:        0x1084f5f3f - <std::thread::local::LocalKey<T>>::try_with::h1f152dfa4c54ac20
                               at libstd/thread/local.rs:294
  34:        0x1084f5aff - <std::thread::local::LocalKey<T>>::with::h7bbf0ea442877021
                               at libstd/thread/local.rs:248
  35:        0x1084df0b2 - <tokio::executor::current_thread::Borrow<'a, U>>::enter::hd44ba9e5e69fa098
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:655
  36:        0x1084df251 - <tokio::executor::current_thread::Entered<'a, P>>::block_on::hb46488ef7b96b0a5
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:444
  37:        0x1084f7be5 - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h51595bd4d2f44eb0
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:234
  38:        0x1084fd195 - tokio_timer::timer::handle::with_default::{{closure}}::h495dedab1b68e332
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.1/src/timer/handle.rs:64
  39:        0x1084f618b - <std::thread::local::LocalKey<T>>::try_with::h2ec5abde3c3dd3bc
                               at libstd/thread/local.rs:294
  40:        0x1084f5a2a - <std::thread::local::LocalKey<T>>::with::h2e114268229e6a29
                               at libstd/thread/local.rs:248
  41:        0x1084fd036 - tokio_timer::timer::handle::with_default::hda972eb157eab1cc
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.1/src/timer/handle.rs:56
  42:        0x1084f7b69 - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::hd868b357ae25388f
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:233
  43:        0x1084f1863 - tokio_executor::global::with_default::{{closure}}::hdb9053c5e96a4dab
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.2/src/global.rs:176
  44:        0x1084f6643 - <std::thread::local::LocalKey<T>>::try_with::hf76baeae916907b6
                               at libstd/thread/local.rs:294
  45:        0x1084f5a9a - <std::thread::local::LocalKey<T>>::with::h5afb9be8ef26d721
                               at libstd/thread/local.rs:248
  46:        0x1084f1711 - tokio_executor::global::with_default::h9052fcf9d2248f95
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.2/src/global.rs:150
  47:        0x1084f7b21 - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::h52bf695bd3680837
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:232
  48:        0x1084e7a95 - tokio_reactor::with_default::{{closure}}::he17143be980a871d
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.1/src/lib.rs:207
  49:        0x1084f63ee - <std::thread::local::LocalKey<T>>::try_with::hbf0ebcd69cee292b
                               at libstd/thread/local.rs:294
  50:        0x1084f59ba - <std::thread::local::LocalKey<T>>::with::h16253fc07ee094b6
                               at libstd/thread/local.rs:248
  51:        0x1084e7916 - tokio_reactor::with_default::hb84e46e493ecb141
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.1/src/lib.rs:199
  52:        0x1084f7ad2 - tokio_core::reactor::Core::run::{{closure}}::h1b901b8da40661ea
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:231
  53:        0x1084e9206 - <scoped_tls::ScopedKey<T>>::set::hd64fc5241a63399b
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:155
  54:        0x1084f77e1 - tokio_core::reactor::Core::run::h88b98bb7d057fcc7
                               at /Users/mh/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:230
  55:        0x108506dae - librespot::main::h2601796f19544f34
                               at src/main.rs:499
  56:        0x1084da1d1 - std::rt::lang_start::{{closure}}::h0ec88bc310830e79
                               at libstd/rt.rs:74
  57:        0x109162fa7 - std::panicking::try::do_call::hcfe6ac53944e0624
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  58:        0x109170cce - macho_symbol_search
                               at libpanic_unwind/lib.rs:103
  59:        0x10915953c - std::sys_common::bytestring::debug_fmt_bytestring::h2a45b81d7d291ba2
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  60:        0x1084da1b1 - std::rt::lang_start::h6dbedc8c2b54facb
                               at libstd/rt.rs:74
  61:        0x108506ea1 - librespot::main::h2601796f19544f34
ERROR:librespot_playback::player: Player thread panicked!
```

**Comment by mherger** [comment]
Seems to have been a Spotify issue: https://twitter.com/SpotifyStatus/status/1068822036154327040?s=20
