### ISSUE TITLE
Librespot crashed after running for hours

### ISSUE THREAD

**Issue by archfan** [librespot-org/librespot#276]
```
INFO:librespot_playback::player: Loading track "What You Want" with Spotify URI "spotify:track:07hS2u7fcY8TLL5Qf6vSN4"
INFO:librespot_playback::player: Track "What You Want" loaded
thread 'main' panicked at 'connection closed', libcore/option.rs:1000:5
stack backtrace:
   0:     0x55c1142b5f2e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hcdfc99915fc0c7a8
   1:     0x55c1142a2796 - std::sys_common::backtrace::print::hf7e2d0bcc5891c8a
   2:     0x55c1142a084d - std::panicking::default_hook::{{closure}}::h521ddaf77f7e7833
   3:     0x55c1142a05c0 - std::panicking::default_hook::hac6c725f3bacc84c
   4:     0x55c1142a0efc - std::panicking::rust_panic_with_hook::heca7ad3f78e76da7
   5:     0x55c1142a0ab9 - std::panicking::continue_panic_fmt::hf8326f9f2bb05559
   6:     0x55c1142a09b5 - rust_begin_unwind
   7:     0x55c1142c856b - core::panicking::panic_fmt::he2ab59e7cd164bb1
   8:     0x55c1142c85e1 - core::option::expect_failed::h10a7a0bb1bbe8de5
   9:     0x55c113f113f3 - <librespot_core::session::DispatchTask<S> as futures::future::Future>::poll::h1db2825621ac9966
  10:     0x55c113f89d71 - <futures::future::join::Join<A, B> as futures::future::Future>::poll::h6417ab070717aff6
  11:     0x55c113fa0206 - <futures::future::map::Map<A, F> as futures::future::Future>::poll::h2b3198c3a0c784c1
  12:     0x55c113f1bfbb - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h028adb6b488b64cb
  13:     0x55c1141d8c5f - futures::task_impl::std::set::h7342ee801a91e8de
  14:     0x55c1141dc2f9 - tokio::executor::current_thread::CurrentRunner::set_spawn::hf8fd3a81d7aefdb9
  15:     0x55c1141e05cc - <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick::hcfde12a3575e8dad
  16:     0x55c1141e22c9 - <scoped_tls::ScopedKey<T>>::set::hed9a9d5a32373fa3
  17:     0x55c1141e1a11 - <std::thread::local::LocalKey<T>>::with::h8968596a39d74915
  18:     0x55c1141e15ca - <std::thread::local::LocalKey<T>>::with::h533125df27009400
  19:     0x55c1141e1478 - <std::thread::local::LocalKey<T>>::with::h259f1f70482b80b1
  20:     0x55c1141dcfbc - tokio_core::reactor::Core::poll::habc6de53be76cb07
  21:     0x55c113e21459 - tokio_core::reactor::Core::run::hd83f42e57ac9e3fe
  22:     0x55c113e2c69a - librespot::main::h9b9861f89a025136
  23:     0x55c113e05b22 - std::rt::lang_start::{{closure}}::h04db20ed88edaa21
  24:     0x55c1142a0952 - std::panicking::try::do_call::h19b660392a3f9d5d
  25:     0x55c1142c4829 - __rust_maybe_catch_panic
  26:     0x55c1142aea05 - std::rt::lang_start_internal::hced735587cc50145
  27:     0x55c113e2d4f3 - main
  28:     0x7f1c3764e09a - __libc_start_main
                               at ../csu/libc-start.c:308
  29:     0x55c113e02b69 - _start
                               at ../sysdeps/x86_64/start.S:120
  30:                0x0 - <unknown>

```

**Comment by snakehead007** [comment]
I've got the same kind of error.
Only get these error after a while when I connect with my phone that is connected to a VPN(without split tunneling) with other devices with VPN (with split tunneling) or without VPN I never get this error.
@archfan  do you use a VPN by chance?

**Comment by l3d00m** [comment]
see also #276

**Comment by aykevl** [comment]
I finally managed to get a tracebace for this issue, see [this gist](https://gist.github.com/aykevl/e22f7a8aa456b6554f4fda142fdc1e96).

I don't use a VPN but I do have a flaky internet connection. I suspect the connection breaks at some point while being paused and the code doesn't know how to deal with it.

**Comment by matthijskooijman** [comment]
This might be related to #247, at least [this comment](https://github.com/librespot-org/librespot/issues/247#issuecomment-454299397) contains pretty much the same backtrace. Might be different from the original reporter in that issue, though.

**Comment by raph2i** [comment]
Same thing here i think?
I can remember, that i connected my Android device at this time to an openvpn server

log:
```
[2019-09-10T15:39:25Z DEBUG librespot_core::session] Session[2] strong=3 weak=4
[2019-09-10T15:41:25Z DEBUG librespot_core::session] Session[2] strong=3 weak=4
[2019-09-10T15:43:25Z DEBUG librespot_core::session] Session[2] strong=3 weak=4
[2019-09-10T15:45:25Z DEBUG librespot_core::session] Session[2] strong=3 weak=4
thread 'main' panicked at 'connection closed', src/libcore/option.rs:1038:5
stack backtrace:
   0:     0x55b03a2ef84f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h15a7d56d2a5865ee
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x55b03a2d9497 - std::sys_common::backtrace::print::h6defabc03a446430
                               at src/libstd/sys_common/backtrace.rs:70
                               at src/libstd/sys_common/backtrace.rs:58
   2:     0x55b03a2f2ca1 - std::panicking::default_hook::{{closure}}::h3c48c92df41c2e69
                               at src/libstd/panicking.rs:200
   3:     0x55b03a2f2a23 - std::panicking::default_hook::hb9b611a3f8c954e3
                               at src/libstd/panicking.rs:215
   4:     0x55b03a2f338f - std::panicking::rust_panic_with_hook::h96432c4e78653b78
                               at src/libstd/panicking.rs:478
   5:     0x55b03a2f2f21 - std::panicking::continue_panic_fmt::hbce0bfb676b70d82
                               at src/libstd/panicking.rs:385
   6:     0x55b03a2f2e05 - rust_begin_unwind
                               at src/libstd/panicking.rs:312
   7:     0x55b03a303bac - core::panicking::panic_fmt::hdf10d4304bc5e576
                               at src/libcore/panicking.rs:85
   8:     0x55b03a303c16 - core::option::expect_failed::h38c960c1b0325e1c
                               at src/libcore/option.rs:1038
   9:     0x55b039fa1cef - <librespot_core::session::DispatchTask<S> as futures::future::Future>::poll::h4cc2983dc3b67f4a
  10:     0x55b039f62046 - <futures::future::join::Join<A, B> as futures::future::Future>::poll::hf678cf53058045cc
  11:     0x55b039fac0e4 - <futures::future::map::Map<A, F> as futures::future::Future>::poll::hb3ebf063e2bd2586
  12:     0x55b039fccbfb - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h0c8a6b983958cc9a
  13:     0x55b03a1f0811 - futures::task_impl::std::set::h231a6e1f02bfaeec
  14:     0x55b03a1ee055 - <futures::task_impl::Spawn<T>>::poll_future_notify::h86be252ee6ece39d
  15:     0x55b03a1fea93 - tokio_current_thread::CurrentRunner::set_spawn::h856fd1b943c8f07e
  16:     0x55b03a1fdf39 - <tokio_current_thread::scheduler::Scheduler<U>>::tick::h2f35461a2af9f9fc
  17:     0x55b03a1ffa54 - <tokio_current_thread::Entered<'a, P>>::turn::h8584b70c615fd834
  18:     0x55b03a1ee91c - <std::thread::local::LocalKey<T>>::with::he72a7d345557952b
  19:     0x55b03a1ee402 - <std::thread::local::LocalKey<T>>::with::h9d23de01ebd43b1c
  20:     0x55b03a1f84a7 - tokio_core::reactor::Core::poll::hb001a216f70b810c
  21:     0x55b039e5b329 - tokio_core::reactor::Core::run::h2bbd199cec8171e8
  22:     0x55b039e59f71 - librespot::main::h53b4abd28989908d
  23:     0x55b039e5c532 - std::rt::lang_start::{{closure}}::h0eb6038486238db0
  24:     0x55b03a2f2da2 - std::panicking::try::do_call::h7288172a5b8f5bc1
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:297
  25:     0x55b03a2f57b9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  26:     0x55b03a2da788 - std::rt::lang_start_internal::h1c10507766312bd5
                               at src/libstd/panicking.rs:276
                               at src/libstd/panic.rs:388
                               at src/libstd/rt.rs:48
  27:     0x55b039e5af01 - main
  28:     0x7f89d50aa228 - <unknown>
[2019-09-10T15:46:23Z DEBUG librespot_core::session] drop Dispatch
[2019-09-10T15:46:23Z DEBUG librespot_connect::spirc] drop Spirc[2]
[2019-09-10T15:46:23Z DEBUG librespot_playback::player] Shutting down player thread ...
[2019-09-10T15:46:23Z DEBUG librespot_playback::player] drop Player[2]
[2019-09-10T15:46:23Z DEBUG librespot_core::session] drop Session[2]
[2019-09-10T15:46:23Z DEBUG librespot_core::audio_key] drop AudioKeyManager
[2019-09-10T15:46:23Z DEBUG librespot_core::channel] drop ChannelManager
[2019-09-10T15:46:23Z DEBUG librespot_core::mercury] drop MercuryManager
```

**Comment by Malvineous** [comment]
Looks like this is covered by #609

**Comment by roderickvd** [comment]
Reconnection logic has been greatly improved, closing for now but feel free to reopen if you still have specific use cases.
