### ISSUE TITLE
Crash on trying to play a particular song

### ISSUE THREAD

**Issue by download13** [librespot-org/librespot#334]
Whenever I try to connect to librespot while playing the song listed in the dump, it crashes. Tried 6 times and it happened consistently every time for this track.

```
May 03 17:49:57 console librespot[7351]: INFO:librespot: librespot (raspotify v0.13.1) 5d2cb32 (2019-04-16). Built on 2019-04-29. Build ID: bQrzTj3V
May 03 17:49:57 console librespot[7351]: INFO:librespot_core::session: Connecting to AP "guc3-accesspoint-a-gmvt.ap.spotify.com:4070"
May 03 17:49:58 console librespot[7351]: INFO:librespot_core::session: Authenticated as "<censored>" !
May 03 17:49:58 console librespot[7351]: INFO:librespot_playback::audio_backend::alsa: Using alsa sink
May 03 17:49:58 console librespot[7351]: INFO:librespot_core::session: Country: "US"
May 03 17:50:42 console librespot[7351]: INFO:librespot_playback::player: Loading track "Caffè" with Spotify URI "spotify:track:66WKuB96Mwmxy9EBiECNp8"
May 03 17:50:44 console librespot[7351]: INFO:librespot_playback::player: Track "Caffè" loaded
May 03 17:50:46 console librespot[7351]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 117, kind: Other, message: "Structure needs cleaning" }', src/libcore/result.rs:997:5
May 03 17:50:46 console librespot[7351]: stack backtrace:
May 03 17:50:46 console librespot[7351]:    0:   0x971fa7 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h71a4d52fb38cd7de
May 03 17:50:46 console librespot[7351]:                        at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
May 03 17:50:46 console librespot[7351]:    1:   0x96d66f - std::sys_common::backtrace::_print::hce8fc7b28ee67394
May 03 17:50:46 console librespot[7351]:                        at src/libstd/sys_common/backtrace.rs:70
May 03 17:50:46 console librespot[7351]:    2:   0x970193 - std::panicking::default_hook::{{closure}}::hdaad4cfa8d5b3133
May 03 17:50:46 console librespot[7351]:                        at src/libstd/sys_common/backtrace.rs:58
May 03 17:50:46 console librespot[7351]:                        at src/libstd/panicking.rs:200
May 03 17:50:46 console librespot[7351]:    3:   0x96fdcf - std::panicking::default_hook::hfb698835042c0732
May 03 17:50:46 console librespot[7351]:                        at src/libstd/panicking.rs:215
May 03 17:50:46 console librespot[7351]:    4:   0x9708bb - std::panicking::rust_panic_with_hook::h25201d3872ea325e
May 03 17:50:46 console librespot[7351]:                        at src/libstd/panicking.rs:478
May 03 17:50:46 console librespot[7351]:    5:   0x97047f - std::panicking::continue_panic_fmt::h44b011030fb5207b
May 03 17:50:46 console librespot[7351]:                        at src/libstd/panicking.rs:385
May 03 17:50:46 console librespot[7351]:    6:   0x97036b - rust_begin_unwind
May 03 17:50:46 console librespot[7351]:                        at src/libstd/panicking.rs:312
May 03 17:50:46 console librespot[7351]:    7:   0x988213 - core::panicking::panic_fmt::hfa7141b9630aa10b
May 03 17:50:46 console librespot[7351]:                        at src/libcore/panicking.rs:85
May 03 17:50:46 console librespot[7351]:    8:   0x63fb33 - core::result::unwrap_failed::h430441f7c4192e19
May 03 17:50:46 console librespot[7351]:    9:   0x62bec3 - librespot_core::cache::Cache::save_file::hc0f555346531d6d2
May 03 17:50:46 console librespot[7351]:   10:   0x580c07 - <futures::future::chain::Chain<A, B, C>>::poll::h967cad95373d45ed
May 03 17:50:46 console librespot[7351]:   11:   0x894b9b - futures::task_impl::std::set::hde5e86308be3dd24
May 03 17:50:46 console librespot[7351]:   12:   0x89214b - <futures::task_impl::Spawn<T>>::poll_future_notify::h04a94cce9611d0f3
May 03 17:50:46 console librespot[7351]:   13:   0x8a45ab - tokio_current_thread::CurrentRunner::set_spawn::h07fb0eeb48b16e9a
May 03 17:50:46 console librespot[7351]:   14:   0x8a3873 - <tokio_current_thread::scheduler::Scheduler<U>>::tick::hab940f358a527526
May 03 17:50:46 console librespot[7351]:   15:   0x8a587f - <tokio_current_thread::Entered<'a, P>>::turn::h42b31b2eeca752f8
May 03 17:50:46 console librespot[7351]:   16:   0x892973 - <std::thread::local::LocalKey<T>>::with::h893eaae605d98f0b
May 03 17:50:46 console librespot[7351]:   17:   0x892297 - <std::thread::local::LocalKey<T>>::with::h41b7ebc6b3ba2dd6
May 03 17:50:46 console systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
May 03 17:50:46 console systemd[1]: raspotify.service: Unit entered failed state.
May 03 17:50:46 console systemd[1]: raspotify.service: Failed with result 'exit-code'.
```

**Comment by kingosticks** [comment]
Are you using the cache? If you google that error ("Structure Needs Cleaning") it takes about filesystem corruption.

**Comment by download13** [comment]
Ah shoot you're totally right. Got some SD card corruption.
