### ISSUE TITLE
Librespot crashed and restarted in the middle of the song

### ISSUE THREAD

**Issue by mordax7** [librespot-org/librespot#338]
Here the log:

```
librespot[581]: INFO:librespot_playback::player: Loading track "Last Nite" with Spotify URI "spotify:track:1zfcJIw2XkBoBSOzLDbiM5"
librespot[581]: ERROR:librespot_core::channel: channel error: 2 1
librespot[581]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ChannelError', src/libcore/result.rs:997:5
librespot[581]: stack backtrace:
librespot[581]:    0:   0x98c6ef - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hba0f000b6e3e84cf
librespot[581]:                        at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
librespot[581]:    1:   0x987db7 - std::sys_common::backtrace::_print::h4fae9ad0cd02baf6
librespot[581]:                        at src/libstd/sys_common/backtrace.rs:70
librespot[581]:    2:   0x98a8db - std::panicking::default_hook::{{closure}}::ha44357031e6e56ad
librespot[581]:                        at src/libstd/sys_common/backtrace.rs:58
librespot[581]:                        at src/libstd/panicking.rs:200
librespot[581]:    3:   0x98a517 - std::panicking::default_hook::hb3ab5986e4d8077e
librespot[581]:                        at src/libstd/panicking.rs:215
librespot[581]:    4:   0x98b003 - std::panicking::rust_panic_with_hook::h035e50f2c01190ff
librespot[581]:                        at src/libstd/panicking.rs:478
librespot[581]:    5:   0x98abc7 - std::panicking::continue_panic_fmt::h6affb6f8230f4c42
librespot[581]:                        at src/libstd/panicking.rs:385
librespot[581]:    6:   0x98aab3 - rust_begin_unwind
librespot[581]:                        at src/libstd/panicking.rs:312
librespot[581]:    7:   0x9a295b - core::panicking::panic_fmt::h472d766e4dff71a2
librespot[581]:                        at src/libcore/panicking.rs:85
librespot[581]:    8:   0x5543c7 - core::result::unwrap_failed::h87f77d2fa5f8e604
librespot[581]:    9:   0x5508cf - librespot_playback::player::PlayerInternal::run::h5d7a49f8609333c1
librespot[581]:   10:   0x4c744b - std::sys_common::backtrace::__rust_begin_short_backtrace::hf54d4e401e169bc5
librespot[581]:   11:   0x4ac21f - std::panicking::try::do_call::h9fbf0de3ec33c852
librespot[581]:   12:   0x99290b - __rust_maybe_catch_panic
librespot[581]:                        at src/libpanic_unwind/lib.rs:87
librespot[581]:   13:   0x4cb15f - <F as alloc::boxed::FnBox<A>>::call_box::h47e276bd4a319f59
librespot[581]:   14:   0x991cf7 - std::sys::unix::thread::Thread::new::thread_start::h3b69f0df0379a30b
librespot[581]:                        at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/liballoc/boxed.rs:759
librespot[581]:                        at src/libstd/sys_common/thread.rs:14
librespot[581]:                        at src/libstd/sys/unix/thread.rs:81
librespot[581]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:997:5
librespot[581]: stack backtrace:
librespot[581]:    0:   0x98c6ef - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hba0f000b6e3e84cf
librespot[581]:                        at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
librespot[581]:    1:   0x987db7 - std::sys_common::backtrace::_print::h4fae9ad0cd02baf6
librespot[581]:                        at src/libstd/sys_common/backtrace.rs:70
librespot[581]:    2:   0x98a8db - std::panicking::default_hook::{{closure}}::ha44357031e6e56ad
librespot[581]:                        at src/libstd/sys_common/backtrace.rs:58
systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
systemd[1]: raspotify.service: Unit entered failed state.
systemd[1]: raspotify.service: Failed with result 'exit-code'.
systemd[1]: raspotify.service: Service hold-off time over, scheduling restart.
systemd[1]: Stopped Raspotify.
systemd[1]: Starting Raspotify...
systemd[1]: Started Raspotify.
```

**Comment by Jakuje** [comment]
I started seeing this as well frequently today.

**Comment by Malvineous** [comment]
Probably the same as #519

**Comment by roderickvd** [comment]
Was an issue Spotify fixed upstream on their end.
