### ISSUE TITLE
Many crashes on Raspberry Pi with latest master

### ISSUE THREAD

**Issue by peterdk** [librespot-org/librespot#407]
I built Raspotify with the latest version of librespot available (f67a38d). I get many times a crash when connecting from my Windows 10 Spotify. 

2 errors are visible in the systemd log. From the looks of it, maybe a issue with the audio device? I did reboot, then it works for a few songs, then crashes again.
```
 [2019-12-06T18:50:18Z INFO  librespot] librespot (raspotify v0.13.1-1-ga7274ae-dirty) f67a38d (2019-12-03). Built on 2019-12-03. Build ID: Pb6mYMeD
dec 06 19:50:18 osmc librespot[295]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 19, kind: Other, message: "No such device" }', src/libcore/result.rs:1165:5
dec 06 19:50:18 osmc librespot[295]: stack backtrace:
dec 06 19:50:18 osmc librespot[295]:    0:   0x98b0e8 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
dec 06 19:50:18 osmc librespot[295]:                        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
dec 06 19:50:18 osmc librespot[295]:    1:   0x98b0e8 - backtrace::backtrace::trace_unsynchronized::h24db1eb743e32b7a
dec 06 19:50:18 osmc librespot[295]:                        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
dec 06 19:50:18 osmc librespot[295]:    2:   0x98b0e8 - std::sys_common::backtrace::_print_fmt::h0ecd5de0be695bc9
dec 06 19:50:18 osmc librespot[295]:                        at src/libstd/sys_common/backtrace.rs:76
dec 06 19:50:18 osmc librespot[295]:    3:   0x98b0e8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf24f776311cdf529
dec 06 19:50:18 osmc librespot[295]:                        at src/libstd/sys_common/backtrace.rs:60
dec 06 19:50:18 osmc librespot[295]:    4:   0x9adb94 - core::fmt::write::h01edf6dd68a42c9c
dec 06 19:50:18 osmc librespot[295]:                        at src/libcore/fmt/mod.rs:1030
dec 06 19:50:18 osmc librespot[295]:    5:   0x985c58 - std::io::Write::write_fmt::ha096f698ec4136ad
dec 06 19:50:18 osmc librespot[295]:                        at src/libstd/io/mod.rs:1412
dec 06 19:50:18 osmc systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
dec 06 19:50:18 osmc systemd[1]: raspotify.service: Unit entered failed state.
dec 06 19:50:18 osmc systemd[1]: raspotify.service: Failed with result 'exit-code'.
````
```
dec 06 20:55:56 osmc librespot[1239]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ChannelError', src/libcore/result.rs:1165:5
dec 06 20:55:56 osmc librespot[1239]: stack backtrace:
dec 06 20:55:56 osmc librespot[1239]:    0:   0x9c5100 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
dec 06 20:55:56 osmc librespot[1239]:                        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
dec 06 20:55:56 osmc librespot[1239]:    1:   0x9c5100 - backtrace::backtrace::trace_unsynchronized::h24db1eb743e32b7a
dec 06 20:55:56 osmc librespot[1239]:                        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
dec 06 20:55:56 osmc librespot[1239]:    2:   0x9c5100 - std::sys_common::backtrace::_print_fmt::h0ecd5de0be695bc9
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/sys_common/backtrace.rs:76
dec 06 20:55:56 osmc librespot[1239]:    3:   0x9c5100 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf24f776311cdf529
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/sys_common/backtrace.rs:60
dec 06 20:55:56 osmc librespot[1239]:    4:   0x9e7bac - core::fmt::write::h01edf6dd68a42c9c
dec 06 20:55:56 osmc librespot[1239]:                        at src/libcore/fmt/mod.rs:1030
dec 06 20:55:56 osmc librespot[1239]:    5:   0x9bfc70 - std::io::Write::write_fmt::ha096f698ec4136ad
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/io/mod.rs:1412
dec 06 20:55:56 osmc librespot[1239]:    6:   0x9c7694 - std::sys_common::backtrace::_print::h4b33c71a5db06ff0
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/sys_common/backtrace.rs:64
dec 06 20:55:56 osmc librespot[1239]:    7:   0x9c7694 - std::sys_common::backtrace::print::h690a5e4a78826230
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/sys_common/backtrace.rs:49
dec 06 20:55:56 osmc librespot[1239]:    8:   0x9c7694 - std::panicking::default_hook::{{closure}}::h9252dff4eab26d22
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/panicking.rs:196
dec 06 20:55:56 osmc librespot[1239]:    9:   0x9c72c0 - std::panicking::default_hook::hf5f567043bc78ff4
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/panicking.rs:210
dec 06 20:55:56 osmc librespot[1239]:   10:   0x9c7d94 - std::panicking::rust_panic_with_hook::h9a662f58cf3f8ffe
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/panicking.rs:473
dec 06 20:55:56 osmc librespot[1239]:   11:   0x9c7994 - std::panicking::continue_panic_fmt::h9fdc31ae90c76747
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/panicking.rs:380
dec 06 20:55:56 osmc librespot[1239]:   12:   0x9c788c - rust_begin_unwind
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/panicking.rs:307
dec 06 20:55:56 osmc librespot[1239]:   13:   0x9e3840 - core::panicking::panic_fmt::h527855ce0bc891f6
dec 06 20:55:56 osmc librespot[1239]:                        at src/libcore/panicking.rs:85
dec 06 20:55:56 osmc librespot[1239]:   14:   0x9e392c - core::result::unwrap_failed::ha8b77e6004f0ba38
dec 06 20:55:56 osmc librespot[1239]:                        at src/libcore/result.rs:1165
dec 06 20:55:56 osmc librespot[1239]:   15:   0x5ca608 - librespot_playback::player::PlayerInternal::run::h5d28bfcd04f75e39
dec 06 20:55:56 osmc librespot[1239]:   16:   0x53f7d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::habc87411fb86cb94
dec 06 20:55:56 osmc librespot[1239]:   17:   0x5190d8 - std::panicking::try::do_call::h6ab0dd0c0ac9bb4c
dec 06 20:55:56 osmc librespot[1239]:   18:   0x9cec48 - __rust_maybe_catch_panic
dec 06 20:55:56 osmc librespot[1239]:                        at src/libpanic_unwind/lib.rs:80
dec 06 20:55:56 osmc librespot[1239]:   19:   0x546d88 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h42873f2ec433f745
dec 06 20:55:56 osmc librespot[1239]:   20:   0x9b8598 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h3879f66a40898a4c
dec 06 20:55:56 osmc librespot[1239]:                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
dec 06 20:55:56 osmc librespot[1239]:   21:   0x9ce0f0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9dc0ea3d0bf5ea71
dec 06 20:55:56 osmc librespot[1239]:                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
dec 06 20:55:56 osmc librespot[1239]:   22:   0x9ce0f0 - std::sys_common::thread::start_thread::hc03f67963ee443cf
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/sys_common/thread.rs:13
dec 06 20:55:56 osmc librespot[1239]:   23:   0x9ce0f0 - std::sys::unix::thread::Thread::new::thread_start::ha181305a817feafa
dec 06 20:55:56 osmc librespot[1239]:                        at src/libstd/sys/unix/thread.rs:79
dec 06 20:55:59 osmc librespot[1239]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
dec 06 20:55:59 osmc systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
dec 06 20:56:00 osmc systemd[1]: raspotify.service: Unit entered failed state.
dec 06 20:56:00 osmc systemd[1]: raspotify.service: Failed with result 'exit-code'.
dec 06 20:56:10 osmc systemd[1]: raspotify.service: Service hold-off time over, scheduling restart.
dec 06 20:56:10 osmc systemd[1]: Stopped Raspotify.
dec 06 20:56:10 osmc systemd[1]: Starting Raspotify...
dec 06 20:56:10 osmc systemd[1]: Started Raspotify.
dec 06 20:56:10 osmc librespot[1254]: [2019-12-06T19:56:10Z INFO  librespot] librespot (raspotify v0.13.1-1-ga7274ae-dirty) f67a38d (2019-12-03). Built on 2019-12-06. Build ID: 4g7Lgo1x
dec 06 21:00:28 osmc librespot[1254]: [2019-12-06T20:00:28Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-a-cs7z.ap.spotify.com:4070"
dec 06 21:00:28 osmc librespot[1254]: [2019-12-06T20:00:28Z INFO  librespot_core::session] Authenticated as "peterdekr" !
dec 06 21:00:28 osmc librespot[1254]: [2019-12-06T20:00:28Z INFO  librespot_playback::audio_backend::alsa] Using alsa sink
dec 06 21:00:28 osmc librespot[1254]: [2019-12-06T20:00:28Z INFO  librespot_core::session] Country: "NL"
dec 06 21:00:29 osmc librespot[1254]: [2019-12-06T20:00:29Z INFO  librespot_playback::player] Loading <Peace of Mind> with Spotify URI <spotify:track:7euSpYKLgtfuMJudod8iwf>
dec 06 21:00:29 osmc librespot[1254]: [2019-12-06T20:00:29Z ERROR librespot_core::channel] channel error: 2 1
dec 06 21:00:29 osmc librespot[1254]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ChannelError', src/libcore/result.rs:1165:5
dec 06 21:00:29 osmc librespot[1254]: stack backtrace:
dec 06 21:00:29 osmc librespot[1254]:    0:   0x943100 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
dec 06 21:00:29 osmc librespot[1254]:                        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
dec 06 21:00:29 osmc librespot[1254]:    1:   0x943100 - backtrace::backtrace::trace_unsynchronized::h24db1eb743e32b7a
dec 06 21:00:29 osmc librespot[1254]:                        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
dec 06 21:00:29 osmc librespot[1254]:    2:   0x943100 - std::sys_common::backtrace::_print_fmt::h0ecd5de0be695bc9
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/sys_common/backtrace.rs:76
dec 06 21:00:29 osmc librespot[1254]:    3:   0x943100 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf24f776311cdf529
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/sys_common/backtrace.rs:60
dec 06 21:00:29 osmc librespot[1254]:    4:   0x965bac - core::fmt::write::h01edf6dd68a42c9c
dec 06 21:00:29 osmc librespot[1254]:                        at src/libcore/fmt/mod.rs:1030
dec 06 21:00:29 osmc librespot[1254]:    5:   0x93dc70 - std::io::Write::write_fmt::ha096f698ec4136ad
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/io/mod.rs:1412
dec 06 21:00:29 osmc librespot[1254]:    6:   0x945694 - std::sys_common::backtrace::_print::h4b33c71a5db06ff0
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/sys_common/backtrace.rs:64
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/sys_common/backtrace.rs:64
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/sys_common/backtrace.rs:64
dec 06 21:00:29 osmc librespot[1254]:    7:   0x945694 - std::sys_common::backtrace::print::h690a5e4a78826230
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/sys_common/backtrace.rs:49
dec 06 21:00:29 osmc librespot[1254]:    8:   0x945694 - std::panicking::default_hook::{{closure}}::h9252dff4eab26d22
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/panicking.rs:196
dec 06 21:00:29 osmc librespot[1254]:    9:   0x9452c0 - std::panicking::default_hook::hf5f567043bc78ff4
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/panicking.rs:210
dec 06 21:00:29 osmc librespot[1254]:   10:   0x945d94 - std::panicking::rust_panic_with_hook::h9a662f58cf3f8ffe
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/panicking.rs:473
dec 06 21:00:29 osmc librespot[1254]:   11:   0x945994 - std::panicking::continue_panic_fmt::h9fdc31ae90c76747
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/panicking.rs:380
dec 06 21:00:29 osmc librespot[1254]:   12:   0x94588c - rust_begin_unwind
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/panicking.rs:307
dec 06 21:00:29 osmc librespot[1254]:   13:   0x961840 - core::panicking::panic_fmt::h527855ce0bc891f6
dec 06 21:00:29 osmc librespot[1254]:                        at src/libcore/panicking.rs:85
dec 06 21:00:29 osmc librespot[1254]:   14:   0x96192c - core::result::unwrap_failed::ha8b77e6004f0ba38
dec 06 21:00:29 osmc librespot[1254]:                        at src/libcore/result.rs:1165
dec 06 21:00:29 osmc librespot[1254]:   15:   0x548608 - librespot_playback::player::PlayerInternal::run::h5d28bfcd04f75e39
dec 06 21:00:29 osmc librespot[1254]:   16:   0x4bd7d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::habc87411fb86cb94
dec 06 21:00:29 osmc librespot[1254]:   17:   0x4970d8 - std::panicking::try::do_call::h6ab0dd0c0ac9bb4c
dec 06 21:00:29 osmc librespot[1254]:   18:   0x94cc48 - __rust_maybe_catch_panic
dec 06 21:00:29 osmc librespot[1254]:                        at src/libpanic_unwind/lib.rs:80
dec 06 21:00:29 osmc librespot[1254]:   19:   0x4c4d88 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h42873f2ec433f745
dec 06 21:00:29 osmc librespot[1254]:   20:   0x936598 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h3879f66a40898a4c
dec 06 21:00:29 osmc librespot[1254]:                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
dec 06 21:00:29 osmc librespot[1254]:   21:   0x94c0f0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9dc0ea3d0bf5ea71
dec 06 21:00:29 osmc librespot[1254]:                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
dec 06 21:00:29 osmc librespot[1254]:   22:   0x94c0f0 - std::sys_common::thread::start_thread::hc03f67963ee443cf
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/sys_common/thread.rs:13
dec 06 21:00:29 osmc librespot[1254]:   23:   0x94c0f0 - std::sys::unix::thread::Thread::new::thread_start::ha181305a817feafa
dec 06 21:00:29 osmc librespot[1254]:                        at src/libstd/sys/unix/thread.rs:79
dec 06 21:00:31 osmc systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
dec 06 21:00:31 osmc systemd[1]: raspotify.service: Unit entered failed state.
```

**Comment by peterdk** [comment]
On 0.1.0 it works flawless. So I reverted to that one.

**Comment by kingosticks** [comment]
Please provide your compile flags and your program arguments. What is 0.1.0? There's no such tag.

**Comment by peterdk** [comment]
`cargo build --release --target arm-unknown-linux-gnueabihf --no-default-features --features alsa-backend
`
`/usr/bin/librespot --name raspotify --backend alsa --bitrate 320 --disable-audio-cache --enable-volume-normalisation --linear-volume --initial-volume=70`

**Comment by SirWindfield** [comment]
It's the bitrate. We got some issues over at spotifyd. You should encounter no errors if you use a lower bitrate like 160 with the newest binary of `librespot`.

**Comment by peterdk** [comment]
@SirWindfield ok, but with the 0.1.0 it works fine? I prefer to use the higher bitrate.

**Comment by SirWindfield** [comment]
It should work fine, yes. I didn't test it myself, but @kingosticks already mentioned it :)

**Comment by peterdk** [comment]
Ok, I think t was caused by issues with XBMC running at the same time as librespot. I disabled XBMC from starting on the pi, and specified the hfiberry device explicitly when starting. I run on latest master now with 320 and it works flawlessly again. Really happy, so no need to switch to something else.
