### ISSUE TITLE
Librespot crashes when started with --autoplay

### ISSUE THREAD

**Issue by MPSMPS** [librespot-org/librespot#420]
Hi,

librespot client always crashes when I start it with the --autoplay option (actual build) as soon as I try to connect to it. According to the log it looks like that the autoplay uri is empty.

Have there been probably some server side changes from spotify?

Thanks!

```
./librespot -n test --autoplay
[2020-01-04T16:40:32Z INFO  librespot] librespot f610436 (2020-01-02). Built on 2020-01-04. Build ID: lwdOAk1I
[2020-01-04T16:40:51Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-a-928c.ap.spotify.com:4070"
[2020-01-04T16:40:51Z INFO  librespot_core::session] Authenticated as "USERNAME REMOVED" !
[2020-01-04T16:40:51Z INFO  librespot_core::session] Country: "DE"
[2020-01-04T16:40:51Z INFO  librespot_connect::spirc] Fetching autoplay context uri
thread 'main' panicked at 'Empty autoplay uri', src/libcore/option.rs:1034:5
stack backtrace:
   0:     0x55d4a44b96c1 - std::sys_common::backtrace::print::ha243869f36df13d3
   1:     0x55d4a44c0e92 - std::panicking::default_hook::{{closure}}::h8c9a444266ff088a
   2:     0x55d4a44c0c23 - std::panicking::default_hook::h8e1ad78046050dae
   3:     0x55d4a44c1580 - std::panicking::rust_panic_with_hook::h1c1e3232dce6ce10
   4:     0x55d4a44c1112 - std::panicking::continue_panic_fmt::h5240cb1767b39889
   5:     0x55d4a44c0ff6 - rust_begin_unwind
   6:     0x55d4a44d69ad - core::panicking::panic_fmt::h412ff536c5029946
   7:     0x55d4a44d8887 - core::option::expect_failed::h7543e0d5501152a9
   8:     0x55d4a40cdc30 - futures::future::chain::Chain<A,B,C>::poll::h358ebcc3e8d74043
   9:     0x55d4a40a26a9 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::he7864c3384769814
  10:     0x55d4a40a843c - <librespot_connect::spirc::SpircTask as futures::future::Future>::poll::h5945fd70adc8b65f
  11:     0x55d4a4068ecc - <librespot::Main as futures::future::Future>::poll::hb54cae949ed497ab
  12:     0x55d4a405159d - futures::task_impl::std::set::h1526394347240d64
  13:     0x55d4a406f224 - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h44b20430978bba49
  14:     0x55d4a405180d - futures::task_impl::std::set::h4e41ede5e07c7658
  15:     0x55d4a404ff23 - std::thread::local::LocalKey<T>::with::h92d72358c237d042
  16:     0x55d4a4050e67 - tokio_current_thread::Entered<P>::block_on::h7001ddc5ef525432
  17:     0x55d4a404fd46 - std::thread::local::LocalKey<T>::with::h4bd27738b4aedbd0
  18:     0x55d4a404f807 - tokio_reactor::with_default::hf06d0e7f45cfb296
  19:     0x55d4a405ec5f - tokio_core::reactor::Core::run::h80a5db31663faef5
  20:     0x55d4a406b84f - librespot::main::h8a32bb8ffeb28489
  21:     0x55d4a404a283 - std::rt::lang_start::{{closure}}::hdb6cd6518c7e9cbb
  22:     0x55d4a44c0f93 - std::panicking::try::do_call::h9626cae8eb53ca10
  23:     0x55d4a44c4dea - __rust_maybe_catch_panic
  24:     0x55d4a44ad969 - std::rt::lang_start_internal::h827bb9874b0abb52
  25:     0x55d4a406c862 - main
  26:     0x7fe68e15eb6b - __libc_start_main
  27:     0x55d4a40401ca - _start
  28:                0x0 - <unknown>
```

**Comment by ashthespy** [comment]
Could you give me more steps to reproduce this? 
Also what client, any particular playlist?

**Comment by devgianlu** [comment]
This usually happens with contexts like `spotify:search:`. In this case, the playback should just be stopped.

**Comment by MPSMPS** [comment]
> Could you give me more steps to reproduce this?
> Also what client, any particular playlist?

Hmm, sorry for the unprecise information. First of all it occurs with the linux spotify client (1.1.10.546.ge08ef575) and the android spotify client (8.5.36.747). So, it looks like it is client independent.

It's actually related somehow to the playlist the song is played from. Where the crash definitely happens is when I choose a song to play from the "liked songs" library. But I was not able to get the conditions when librespot crashes regarding the playlist. The probability that a playlist is working is lower when it was created by me. So official playlists work better, but not all. But I also have some private playlists that are working. Any further indicators I could look at to get more precise information?

Steps to reproduce:

1. start playing song on client with local output (e.g. android spotify client by using phone's speakers)
2. switch in the client to use another device (in this case librespot) and exact in that moment librespot crashes depending on the chosen playlist (see above)

**Comment by ashthespy** [comment]
@devgianlu When do get context like `spotify:search:`? Even when I'm in the search menu, the track only contains the album context?

@MPSMPS  can you share logs of the crash with the `--verbose` flag enabled? I still am not able to recreate this - does your playlist contain local tracks?

**Comment by devgianlu** [comment]
> @devgianlu When do get context like spotify:search:? Even when I'm in the search menu, the track only contains the album context?

Don't quite remember, it might be a thing related with older versions (like the being used by @MPSMPS on Linux).

BTW, I see you are using `hm://autoplay-enabled/query?={uri}`, but `hm://radio-apollo/v3/stations/{uri}` also works pretty well.

**Comment by MPSMPS** [comment]
Please find the log below.

As far as I am aware of my playlist does not contain local tracks. Since the playlist has grown over a long time I can't guarantee this :-/

I tried something else: I selected all files from my "liked songs" and created a new playlist from these songs. Then I started playback from this new playlist and then switched to librespot-client. And then it worked without crashing. It looks like it really has something to do with that "liked songs"-thing from spotify. Have you tried to playback from the liked songs category?

@devgianlu The linux client is maybe old but I also quit it on my notebook. On the notebook the librespot client is running and I am doing the playback/choosing playback device with my android smartphone. So that client should be reasonably new.

The autoplay option is not essential for me. Nevertheless, it would be a nice feature.

```
./librespot -n test --autoplay --verbose
[2020-01-06T18:38:51Z INFO  librespot] librespot f610436 (2020-01-02). Built on 2020-01-04. Build ID: lwdOAk1I
[2020-01-06T18:38:51Z DEBUG librespot_connect::discovery] Zeroconf server listening on 0.0.0.0:39215
[2020-01-06T18:39:13Z DEBUG librespot_connect::discovery] Post "/" {}
[2020-01-06T18:39:13Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-a-mv5f.ap.spotify.com:4070"
[2020-01-06T18:39:13Z INFO  librespot_core::session] Authenticated as "MYSPOTIFYUSERNAME" !
[2020-01-06T18:39:13Z DEBUG librespot_core::session] new Session[0]
[2020-01-06T18:39:13Z DEBUG librespot_connect::spirc] new Spirc[0]
[2020-01-06T18:39:13Z DEBUG librespot_core::mercury] new MercuryManager
[2020-01-06T18:39:13Z DEBUG librespot_playback::player] new Player[0]
[2020-01-06T18:39:13Z DEBUG librespot_playback::audio_backend::rodio] Using rodio sink
[2020-01-06T18:39:13Z DEBUG librespot_connect::spirc] input volume:32768 to mixer: 2072
[2020-01-06T18:39:13Z DEBUG librespot_core::session] Session[0] strong=3 weak=2
[2020-01-06T18:39:13Z INFO  librespot_core::session] Country: "DE"
[2020-01-06T18:39:13Z DEBUG librespot_core::mercury] unknown subscription uri=hm://remote/user/MYSPOTIFYUSERNAME/
[2020-01-06T18:39:13Z DEBUG librespot_core::mercury] unknown subscription uri=hm://remote/user/MYSPOTIFYUSERNAME/
[2020-01-06T18:39:13Z DEBUG librespot_core::mercury] unknown subscription uri=hm://remote/user/MYSPOTIFYUSERNAME/
[2020-01-06T18:39:13Z DEBUG librespot_core::mercury] subscribed uri=hm://remote/user/MYSPOTIFYUSERNAME/ count=0
[2020-01-06T18:39:13Z DEBUG librespot_connect::spirc] kMessageTypeNotify "librespot" 7c28ab8a5c9512e4266ac7cb756312c82ee43d7e 2082956368 1578335953266
[2020-01-06T18:39:13Z DEBUG librespot_connect::spirc] kMessageTypeLoad "SM-G930F" adeedfd69f4cb2cd4eacc7df0eed5b0ca02013d8 2082956515 1578335953266
[2020-01-06T18:39:13Z DEBUG librespot_connect::spirc] State: context_uri: "spotify:user:MYSPOTIFYUSERNAME:collection" index: 2 position_ms: 62959 status: kPlayStatusPlay position_measured_at: 1578335953449 context_description: "" shuffle: false repeat: false playing_from_fallback: true row: 0 playing_track_index: 2 track {gid: "\305\267\312\351\201\347J\000\227\200\241Sl\314\2646"} track {gid: "+\312\367\035\344\221A\001\265qV\374\270\244i|"} track {gid: "\213\376\214G<\303D\200\243\377\230\226\360-NS"} track {gid: "i\342\266j\345\001E\237\230\316\342;\322\241&B"} track {gid: "2p\311s\316\336E\365\256g\361\255+\371\211\260"} track {gid: "\227\247\247\356*\rA?\257\001\376\256\245Y\236\313"} track {gid: "nnz\315\020+B\030\223\324\262b\3318\215J"} track {gid: "h\233\216\255_\203M\350\223\327]p\260\342\257\340"} track {gid: "2\330G<\353,LR\237\347\301\316\373f\263\350"} track {gid: "w\023\350\313/\355H\352\2764\344\r\366!\320\234"} track {gid: "\3421\255\010]\221I\327\203\335\r\230\356+U\355"} track {gid: ".\016\n\364\260\220D\243\210\334VZ\335\356\254\257"} track {gid: "5:\260\007\314\nF0\236*\230\374f\356\267s"} track {gid: "4q\232\035J\005F\236\236\237\357\005.p\376\r"} track {gid: "\365.5\215\312\272I%\252\033\307\233\022$\\\337"} track {gid: "\267d\351\257\004\352C\002\202[\210:@\006\3754"} track {gid: "\027:\250\232\2304Dy\240T\262\376\226\354U\350"} track {gid: "\263[\034\246\271\020J\355\243k\023J\017:\004\027"} track {gid: "\\\353G\374\032\343N\037\261\203\022\270\244C\374\003"} track {gid: "Re[\242\301\032O\313\264\024\361Q|\340j\024"} track {gid: "F\370wU1\240H\237\273\026\356}\264|\3753"} track {gid: "C5\234\276\\\035J\\\212\351\224q\331\030v\254"} track {gid: "cXa\262\021\220EJ\277Zr\252\006\254\241n"} track {gid: "\\\357\330E\230\266F\356\262\252d~ l\r\232"} track {gid: "\353\037F:+\213L\264\255\004\243IN$\325\225"} track {gid: "\035\300\342\240-\246HD\214TL\203\006'\"\213"} track {gid: "RR\356\316wOA\205\246g\337\001\220\306m0"} track {gid: "x\366\260\022\322fL\030\255.\302\204\332\356\307\024"} track {gid: "\0143\301\224\3730H\335\2546\236\304*\316\017\355"} track {gid: "h\252\360\351\200;C\033\233\347\205l\373\211Ek"} track {gid: "5\"\036\206\016\327I\252\256\\.\2646\002i\201"} track {gid: "\214\354\236/\302\347@\251\207\375i\212\3102\210\005"} track {gid: "\221\335\337}\320vN\225\203\316G\211\250\245\326\257"} track {gid: "\243\256\203\332\245WO\222\265B\326\037\031y4S"} track {gid: "\271J\374K\304&F\212\236\230\271\025\"&7\n"} track {gid: "\267\250\330\222\213\006K\376\213\333e@F\210(z"} track {gid: "uwyq\352\374C\323\227e\330\231\274wk\211"} track {gid: "\3239\337\304<gGi\264\270V{\263\031&\222"} track {gid: "P\302\261[pDH^\244V\273\022\355\346pb"} track {gid: "H\222lf:\310E.\246\311\277\374\"\327d\356"} track {gid: ":\302\224IIsN)\221\237;\242\326a\2315"} track {gid: "\375\232\300\031|\205B\234\233\027\314\"9\205\266T"} track {gid: "\272\024\313\264\254\tHN\200\177F:\256\354'v"} track {gid: "\307\337\201\363h\242F\265\251n\3228\367\375lr"} track {gid: "\331V+\367m\260G\327\235(\2677\375\275\344\224"} track {gid: "\036\342x\257\372FI\315\210\266\237\363\233I\353\306"} track {gid: "\304j\215\345\225\363C,\231\006\014\352\331bl:"} track {gid: "\305\0345M!\232@N\221\277\370\344\263fQ\240"} track {gid: "\177\212\311\361\031HD\336\207M~\035\014ZVT"} track {gid: "\316[\002\222\3704J*\2157V\336\344\266\351\314"} track {gid: "]\203>h+\206O\260\247\372\253\233a\2062\037"} track {gid: "\r\252\266\360\325\300C+\206\366\020\272\177yFT"} track {gid: "\213\004\305\027\335\236H\001\201\r\307\004N\366\304\306"} track {gid: "\256P]\310\203\310O\242\273\3326\362\242`\217\034"} track {gid: "\320\351\020\240\016\227I>\266 \214\236\373\366\023\316"} track {gid: "JC@\356]\226@]\244\215y>\343\251\2615"} track {gid: "H\222m\037\275~D\274\272\306\005\207_\222*\240"} track {gid: "/N5S\271\252N\333\2213\030\306]\272:n"} track {gid: "0\323t59\271I\200\261x\210\244:*I="} track {gid: "\021\255\365e\243\332H_\222J\336*\013.\"\351"} track {gid: "\307u=t\204wG\214\256/@j{Z\375\320"} track {gid: "\325\232\007g\254\232Aw\221y4\261zM3\222"} track {gid: "\216\373\030)(NO\036\236\374\2401!D\331("} track {gid: "\307\274\344kVMI\313\243\212VV^\027'\301"} track {gid: "^\346\002\301\264\177E\362\213|\232q\371\201\200\023"} track {gid: "\272yY\330\273\016M\366\220\341\367\301\327\tHx"} track {gid: "\211\230\222\364\234\265J/\225u\242\233\341H\253\236"} track {gid: "z\312MT\231\335EB\234}\223])\226>\317"} track {gid: "\256\260\301\303\031\306MO\254\002\343]=\220+\206"} track {gid: "\n3d\027\366\355@\363\275\002LO\030\025-\330"} track {gid: "\035\204\264\2025\001@i\231g\033\203\274$\304\365"} track {gid: "\212>\247R\253\034O\374\264\323\317,+pbE"} track {gid: "\232Mz \262\277F\321\254\021]\375`M4\014"} track {gid: "\244\260\303BD#GP\256\316`\021`L4\361"} track {gid: "\261\272@e!\324M\261\276\355|X4Y\273\331"} track {gid: "p.\362:\324\nH>\253hma\212u\353b"} track {gid: "t\n\341)S)CX\251\340\033\342\237`\255\274"} track {gid: "\"\r\342\323G\335F\013\251h/\207,a\"i"} track {gid: "N\202\366 ~\232@Z\241\344\240\020\014x\274|"} track {gid: "\240X\322\240\247\203E\307\204\362\021\375kz\003\365"} track {gid: "\201\304\227\313\212\324E\350\265\200\035C\265=\252\006"}
[2020-01-06T18:39:13Z DEBUG librespot_connect::spirc] Frame has 81 tracks
[2020-01-06T18:39:13Z INFO  librespot_connect::spirc] Fetching autoplay context uri
[2020-01-06T18:39:13Z DEBUG librespot_connect::spirc] Loading context: <spotify:user:MYSPOTIFYUSERNAME:collection> index: [2] of 81
[2020-01-06T18:39:13Z DEBUG librespot_playback::player] command=Load(SpotifyId { id: 186084379997520366915930214307927510611, audio_type: Track }, true, 62959)
thread 'main' panicked at 'Empty autoplay uri', src/libcore/option.rs:1034:5
stack backtrace:
   0:     0x558deac806c1 - std::sys_common::backtrace::print::ha243869f36df13d3
   1:     0x558deac87e92 - std::panicking::default_hook::{{closure}}::h8c9a444266ff088a
   2:     0x558deac87c23 - std::panicking::default_hook::h8e1ad78046050dae
   3:     0x558deac88580 - std::panicking::rust_panic_with_hook::h1c1e3232dce6ce10
   4:     0x558deac88112 - std::panicking::continue_panic_fmt::h5240cb1767b39889
   5:     0x558deac87ff6 - rust_begin_unwind
   6:     0x558deac9d9ad - core::panicking::panic_fmt::h412ff536c5029946
   7:     0x558deac9f887 - core::option::expect_failed::h7543e0d5501152a9
   8:     0x558dea894c30 - futures::future::chain::Chain<A,B,C>::poll::h358ebcc3e8d74043
   9:     0x558dea8696a9 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::he7864c3384769814
  10:     0x558dea86f43c - <librespot_connect::spirc::SpircTask as futures::future::Future>::poll::h5945fd70adc8b65f
  11:     0x558dea82fecc - <librespot::Main as futures::future::Future>::poll::hb54cae949ed497ab
  12:     0x558dea81859d - futures::task_impl::std::set::h1526394347240d64
  13:     0x558dea836224 - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h44b20430978bba49
  14:     0x558dea81880d - futures::task_impl::std::set::h4e41ede5e07c7658
  15:     0x558dea816f23 - std::thread::local::LocalKey<T>::with::h92d72358c237d042
  16:     0x558dea817e67 - tokio_current_thread::Entered<P>::block_on::h7001ddc5ef525432
  17:     0x558dea816d46 - std::thread::local::LocalKey<T>::with::h4bd27738b4aedbd0
  18:     0x558dea816807 - tokio_reactor::with_default::hf06d0e7f45cfb296
  19:     0x558dea825c5f - tokio_core::reactor::Core::run::h80a5db31663faef5
  20:     0x558dea83284f - librespot::main::h8a32bb8ffeb28489
  21:     0x558dea811283 - std::rt::lang_start::{{closure}}::hdb6cd6518c7e9cbb
  22:     0x558deac87f93 - std::panicking::try::do_call::h9626cae8eb53ca10
  23:     0x558deac8bdea - __rust_maybe_catch_panic
  24:     0x558deac74969 - std::rt::lang_start_internal::h827bb9874b0abb52
  25:     0x558dea833862 - main
  26:     0x7fa87442bb6b - __libc_start_main
  27:     0x558dea8071ca - _start
  28:                0x0 - <unknown>
[2020-01-06T18:39:13Z DEBUG librespot_connect::spirc] drop Spirc[0]
[2020-01-06T18:39:13Z DEBUG librespot_playback::player] Shutting down player thread ...
```

**Comment by devgianlu** [comment]
I've just checked and autoplay for the liked songs doesn't work on librespot-java either. This is an API limitation, the only thing to do here is not to crash but pause the playback instead.

**Comment by ashthespy** [comment]
> BTW, I see you are using `hm://autoplay-enabled/query?={uri}`, but `hm://radio-apollo/v3/stations/{uri}` also works pretty well ([my implementation](https://github.com/librespot-org/librespot-java/blob/b4d6476f49c81dc7db8f6d2c22bd7ead0a2a0095/core/src/main/java/xyz/gianlu/librespot/player/Player.java#L553)).

The `autoplay-enabled` endpoint was what we reversed from the client, but at the end of the day, its is indeed just a `radio-apollo` based dynamic playlist. 

>I've just checked and autoplay for the liked songs doesn't work on librespot-java either. This is an API limitation, the only thing to do here is not to crash but pause the playback instead.

Should be the same in the implementation here - `spotify:username:collection` doesn't seem return and tracks from both 

@MPSMPS What track is `186084379997520366915930214307927510611`? I am not able to extract any metdata for it via Spotify's API, which would be the reason for the panic.  

```
[2020-01-06T19:54:05Z WARN  librespot_core::mercury] error 404 for uri hm://metadata/4/track/186084379997520366915930214307927510611
```

**Comment by MPSMPS** [comment]
This is the spotify URI: spotify:track:4gagfSo6yKtWXDicu2oIcr
But I think it is independent from the chosen song.

This is the log when starting librespot without --autoplay and playing the same song:
./librespot -n test --verbose
```
[2020-01-06T21:16:27Z INFO  librespot] librespot f610436 (2020-01-02). Built on 2020-01-04. Build ID: lwdOAk1I
[2020-01-06T21:16:27Z DEBUG librespot_connect::discovery] Zeroconf server listening on 0.0.0.0:38897
[2020-01-06T21:17:15Z DEBUG librespot_connect::discovery] Post "/" {}
[2020-01-06T21:17:15Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-a-0pfb.ap.spotify.com:4070"
[2020-01-06T21:17:15Z INFO  librespot_core::session] Authenticated as "MYSPOTIFYUSERNAME" !
[2020-01-06T21:17:15Z DEBUG librespot_core::session] new Session[0]
[2020-01-06T21:17:15Z DEBUG librespot_connect::spirc] new Spirc[0]
[2020-01-06T21:17:15Z DEBUG librespot_core::mercury] new MercuryManager
[2020-01-06T21:17:15Z DEBUG librespot_playback::player] new Player[0]
[2020-01-06T21:17:15Z DEBUG librespot_playback::audio_backend::rodio] Using rodio sink
[2020-01-06T21:17:15Z DEBUG librespot_connect::spirc] input volume:32768 to mixer: 2072
[2020-01-06T21:17:15Z DEBUG librespot_core::session] Session[0] strong=3 weak=2
[2020-01-06T21:17:15Z INFO  librespot_core::session] Country: "DE"
[2020-01-06T21:17:15Z DEBUG librespot_core::mercury] unknown subscription uri=hm://remote/user/MYSPOTIFYUSERNAME/
[2020-01-06T21:17:15Z DEBUG librespot_core::mercury] subscribed uri=hm://remote/user/MYSPOTIFYUSERNAME/ count=0
[2020-01-06T21:17:15Z DEBUG librespot_connect::spirc] kMessageTypeNotify "mpsmps" babdfe07df10f07c016313819937295bc53a3848 2092438628 1578345435526
[2020-01-06T21:17:15Z DEBUG librespot_connect::spirc] kMessageTypeLoad "SM-G930F" adeedfd69f4cb2cd4eacc7df0eed5b0ca02013d8 2092438744 1578345435526
[2020-01-06T21:17:15Z DEBUG librespot_connect::spirc] State: context_uri: "spotify:user:MYSPOTIFYUSERNAME:collection" index: 2 position_ms: 34404 status: kPlayStatusPlay position_measured_at: 1578345435689 context_description: "" shuffle: false repeat: false playing_from_fallback: true row: 0 playing_track_index: 2 track {gid: "\305\267\312\351\201\347J\000\227\200\241Sl\314\2646"} track {gid: "+\312\367\035\344\221A\001\265qV\374\270\244i|"} track {gid: "\213\376\214G<\303D\200\243\377\230\226\360-NS"} track {gid: "i\342\266j\345\001E\237\230\316\342;\322\241&B"} track {gid: "2p\311s\316\336E\365\256g\361\255+\371\211\260"} track {gid: "\227\247\247\356*\rA?\257\001\376\256\245Y\236\313"} track {gid: "nnz\315\020+B\030\223\324\262b\3318\215J"} track {gid: "h\233\216\255_\203M\350\223\327]p\260\342\257\340"} track {gid: "2\330G<\353,LR\237\347\301\316\373f\263\350"} track {gid: "w\023\350\313/\355H\352\2764\344\r\366!\320\234"} track {gid: "\3421\255\010]\221I\327\203\335\r\230\356+U\355"} track {gid: ".\016\n\364\260\220D\243\210\334VZ\335\356\254\257"} track {gid: "5:\260\007\314\nF0\236*\230\374f\356\267s"} track {gid: "4q\232\035J\005F\236\236\237\357\005.p\376\r"} track {gid: "\365.5\215\312\272I%\252\033\307\233\022$\\\337"} track {gid: "\267d\351\257\004\352C\002\202[\210:@\006\3754"} track {gid: "\027:\250\232\2304Dy\240T\262\376\226\354U\350"} track {gid: "\263[\034\246\271\020J\355\243k\023J\017:\004\027"} track {gid: "\\\353G\374\032\343N\037\261\203\022\270\244C\374\003"} track {gid: "Re[\242\301\032O\313\264\024\361Q|\340j\024"} track {gid: "F\370wU1\240H\237\273\026\356}\264|\3753"} track {gid: "C5\234\276\\\035J\\\212\351\224q\331\030v\254"} track {gid: "cXa\262\021\220EJ\277Zr\252\006\254\241n"} track {gid: "\\\357\330E\230\266F\356\262\252d~ l\r\232"} track {gid: "\353\037F:+\213L\264\255\004\243IN$\325\225"} track {gid: "\035\300\342\240-\246HD\214TL\203\006'\"\213"} track {gid: "RR\356\316wOA\205\246g\337\001\220\306m0"} track {gid: "x\366\260\022\322fL\030\255.\302\204\332\356\307\024"} track {gid: "\0143\301\224\3730H\335\2546\236\304*\316\017\355"} track {gid: "h\252\360\351\200;C\033\233\347\205l\373\211Ek"} track {gid: "5\"\036\206\016\327I\252\256\\.\2646\002i\201"} track {gid: "\214\354\236/\302\347@\251\207\375i\212\3102\210\005"} track {gid: "\221\335\337}\320vN\225\203\316G\211\250\245\326\257"} track {gid: "\243\256\203\332\245WO\222\265B\326\037\031y4S"} track {gid: "\271J\374K\304&F\212\236\230\271\025\"&7\n"} track {gid: "\267\250\330\222\213\006K\376\213\333e@F\210(z"} track {gid: "uwyq\352\374C\323\227e\330\231\274wk\211"} track {gid: "\3239\337\304<gGi\264\270V{\263\031&\222"} track {gid: "P\302\261[pDH^\244V\273\022\355\346pb"} track {gid: "H\222lf:\310E.\246\311\277\374\"\327d\356"} track {gid: ":\302\224IIsN)\221\237;\242\326a\2315"} track {gid: "\375\232\300\031|\205B\234\233\027\314\"9\205\266T"} track {gid: "\272\024\313\264\254\tHN\200\177F:\256\354'v"} track {gid: "\307\337\201\363h\242F\265\251n\3228\367\375lr"} track {gid: "\331V+\367m\260G\327\235(\2677\375\275\344\224"} track {gid: "\036\342x\257\372FI\315\210\266\237\363\233I\353\306"} track {gid: "\304j\215\345\225\363C,\231\006\014\352\331bl:"} track {gid: "\305\0345M!\232@N\221\277\370\344\263fQ\240"} track {gid: "\177\212\311\361\031HD\336\207M~\035\014ZVT"} track {gid: "\316[\002\222\3704J*\2157V\336\344\266\351\314"} track {gid: "]\203>h+\206O\260\247\372\253\233a\2062\037"} track {gid: "\r\252\266\360\325\300C+\206\366\020\272\177yFT"} track {gid: "\213\004\305\027\335\236H\001\201\r\307\004N\366\304\306"} track {gid: "\256P]\310\203\310O\242\273\3326\362\242`\217\034"} track {gid: "\320\351\020\240\016\227I>\266 \214\236\373\366\023\316"} track {gid: "JC@\356]\226@]\244\215y>\343\251\2615"} track {gid: "H\222m\037\275~D\274\272\306\005\207_\222*\240"} track {gid: "/N5S\271\252N\333\2213\030\306]\272:n"} track {gid: "0\323t59\271I\200\261x\210\244:*I="} track {gid: "\021\255\365e\243\332H_\222J\336*\013.\"\351"} track {gid: "\307u=t\204wG\214\256/@j{Z\375\320"} track {gid: "\325\232\007g\254\232Aw\221y4\261zM3\222"} track {gid: "\216\373\030)(NO\036\236\374\2401!D\331("} track {gid: "\307\274\344kVMI\313\243\212VV^\027'\301"} track {gid: "^\346\002\301\264\177E\362\213|\232q\371\201\200\023"} track {gid: "\272yY\330\273\016M\366\220\341\367\301\327\tHx"} track {gid: "\211\230\222\364\234\265J/\225u\242\233\341H\253\236"} track {gid: "z\312MT\231\335EB\234}\223])\226>\317"} track {gid: "\256\260\301\303\031\306MO\254\002\343]=\220+\206"} track {gid: "\n3d\027\366\355@\363\275\002LO\030\025-\330"} track {gid: "\035\204\264\2025\001@i\231g\033\203\274$\304\365"} track {gid: "\212>\247R\253\034O\374\264\323\317,+pbE"} track {gid: "\232Mz \262\277F\321\254\021]\375`M4\014"} track {gid: "\244\260\303BD#GP\256\316`\021`L4\361"} track {gid: "\261\272@e!\324M\261\276\355|X4Y\273\331"} track {gid: "p.\362:\324\nH>\253hma\212u\353b"} track {gid: "t\n\341)S)CX\251\340\033\342\237`\255\274"} track {gid: "\"\r\342\323G\335F\013\251h/\207,a\"i"} track {gid: "N\202\366 ~\232@Z\241\344\240\020\014x\274|"} track {gid: "\240X\322\240\247\203E\307\204\362\021\375kz\003\365"} track {gid: "\201\304\227\313\212\324E\350\265\200\035C\265=\252\006"} track {gid: "[L\300\335\007\003D\022\235\217XBDu#d"} track {gid: "\370_RX\336)Kh\245{\031\372jN4\261"}
[2020-01-06T21:17:15Z DEBUG librespot_connect::spirc] Frame has 83 tracks
[2020-01-06T21:17:15Z DEBUG librespot_connect::spirc] Loading context: <spotify:user:MYSPOTIFYUSERNAME:collection> index: [2] of 83
[2020-01-06T21:17:15Z DEBUG librespot_playback::player] command=Load(SpotifyId { id: 186084379997520366915930214307927510611, audio_type: Track }, true, 34404)
[2020-01-06T21:17:15Z INFO  librespot_playback::player] Loading <Do You Want Me> with Spotify URI <spotify:track:4gagfSo6yKtWXDicu2oIcr>
[2020-01-06T21:17:15Z DEBUG librespot_core::audio_key] new AudioKeyManager
[2020-01-06T21:17:15Z DEBUG librespot_audio::fetch] Downloading file 7fb82aad5e09e18a5ff561be166779ddb348ca5d
[2020-01-06T21:17:15Z DEBUG librespot_core::channel] new ChannelManager
[2020-01-06T21:17:15Z TRACE librespot_audio::fetch] Ping time estimated as: 41 ms.
[2020-01-06T21:17:15Z DEBUG librespot_playback::player] Normalisation Data: NormalisationData { track_gain_db: -2.209999, track_peak: 1.0500089, album_gain_db: -8.099998, album_peak: 1.1931204 }
[2020-01-06T21:17:15Z DEBUG librespot_playback::player] Applied normalisation factor: 0.775354
[2020-01-06T21:17:15Z DEBUG librespot_connect::spirc] kMessageTypeNotify "SM-G930F" adeedfd69f4cb2cd4eacc7df0eed5b0ca02013d8 2092438962 1578345435860
[2020-01-06T21:17:15Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:15Z INFO  librespot_playback::player] <Do You Want Me> loaded
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 24 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 22 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 20 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 22 ms.
[2020-01-06T21:17:16Z TRACE librespot_audio::fetch] Ping time estimated as: 21 ms.
[2020-01-06T21:17:20Z DEBUG librespot_audio::fetch] File 7fb82aad5e09e18a5ff561be166779ddb348ca5d complete
```

**Comment by ashthespy** [comment]
Sorry for the wild goose debugging chase, I was being daft. Above commit should fix such issues.

**Comment by MPSMPS** [comment]
@ashthespy cool, thank you. I built it with your fix and so far no crash. Just a warning and error line but that's coming from your new piece of code.
