### ISSUE TITLE
Impossible to play some tracks

### ISSUE THREAD

**Issue by asirinelli** [librespot-org/librespot#464]
Hi,

I have realised that since a couple of days librespot is not able to play some tracks.

When I start playing the track from the up-to-date Spotify android app or from open.spotify.com, nothing happen and only the following line is found in the log (each time I request playing):

```
(Spotify) [2020-04-18T19:53:54Z INFO  librespot_connect::spirc] No more tracks left in queue
```

I am using librespot compiled today on commit ef27b4bce371d0a41e7ee2263244ed141684ff9b running from a snapcast server on a raspberry pi 3 (armv7l).

An example of track impossible to be played: track/0J2p4KYdr6Mg4ET6JPlbe1

Antoine

**Comment by tysonnorris** [comment]
I'm getting the same issue, except it happens with all tracks. 
I'm starting librespot as 
```
pi@raspberrypi:~ $ sudo librespot -n "Librespot Speaker" -b 160 --device "sysdefault:CARD=sndrpihifiberry"
[2020-08-15T18:52:57Z INFO  librespot] librespot (raspotify v0.14.0) 6aac8a6 (2020-07-24). Built on 2020-07-26. Build ID: wPNyqn0m
[2020-08-15T18:53:04Z INFO  librespot_core::session] Connecting to AP "guc3-accesspoint-b-bmgb.ap.spotify.com:4070"
[2020-08-15T18:53:05Z INFO  librespot_core::session] Authenticated as "noizenheimer" !
[2020-08-15T18:53:05Z INFO  librespot_playback::audio_backend::alsa] Using alsa sink
[2020-08-15T18:53:05Z INFO  librespot_core::session] Country: "US"
[2020-08-15T18:53:05Z INFO  librespot_connect::spirc] No more tracks left in queue
```
and no audio seems to arrive at my raspberry pi. 

Also noteworthy
* I'm starting song play from spotify ios app
* librespot does the same whether song is started before or after selecting device
* if I advance the track on ios app: `[2020-08-15T18:55:00Z INFO  librespot_connect::spirc] Not playing next track because there are no more tracks left in queue.`
* if I skip to previous track on the ios app: 
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', connect/src/spirc.rs:1159:29
stack backtrace:
   0:   0x88b584 - backtrace::backtrace::libunwind::trace::had1ce870e7642f03
                       at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:   0x88b584 - backtrace::backtrace::trace_unsynchronized::he46c884781dd51a8
                       at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:   0x88b584 - std::sys_common::backtrace::_print_fmt::h621902e5e498623c
                       at src/libstd/sys_common/backtrace.rs:78
   3:   0x88b584 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h39c43d9eea8febb9
                       at src/libstd/sys_common/backtrace.rs:59
   4:   0x8b2e88 - core::fmt::write::h1faa4c62c7847860
                       at src/libcore/fmt/mod.rs:1076
   5:   0x884cd4 - std::io::Write::write_fmt::h1d02362bb0653180
                       at src/libstd/io/mod.rs:1537
   6:   0x88de68 - std::sys_common::backtrace::_print::hb6e6bf916a89634f
                       at src/libstd/sys_common/backtrace.rs:62
   7:   0x88de68 - std::sys_common::backtrace::print::h70b0c25b24fd7afb
                       at src/libstd/sys_common/backtrace.rs:49
   8:   0x88de68 - std::panicking::default_hook::{{closure}}::hc261daa3190f9e66
                       at src/libstd/panicking.rs:198
   9:   0x88db1c - std::panicking::default_hook::h5ce743d47ceb319b
                       at src/libstd/panicking.rs:218
  10:   0x88e520 - std::panicking::rust_panic_with_hook::hb609da6fd4918712
                       at src/libstd/panicking.rs:486
  11:   0x88e13c - rust_begin_unwind
                       at src/libstd/panicking.rs:388
  12:   0x8b0560 - core::panicking::panic_fmt::h48562d60f069801a
                       at src/libcore/panicking.rs:101
  13:   0x8b0528 - core::panicking::panic_bounds_check::hf394c8ac15a6104f
                       at src/libcore/panicking.rs:73
  14:   0x4c4f18 - librespot_connect::spirc::SpircTask::get_track_id_to_play_from_playlist::h185a7b661a1f479c
  15:   0x4c4fb4 - librespot_connect::spirc::SpircTask::load_track::h26596fdb8ba8975f
  16:   0x4c4100 - librespot_connect::spirc::SpircTask::handle_prev::h7370911a77585fd3
  17:   0x4c1d0c - <librespot_connect::spirc::SpircTask as futures::future::Future>::poll::hca2e59f6ce090749
  18:   0x479534 - <librespot::Main as futures::future::Future>::poll::hb6066ad006e6f68c
  19:   0x47fc68 - futures::task_impl::std::set::h084e6325663de6f9
  20:   0x47fec4 - futures::task_impl::std::set::h3c32452dee050335
  21:   0x461e48 - std::thread::local::LocalKey<T>::with::ha70cd7ac97d797ba
  22:   0x45dfb4 - tokio_current_thread::Entered<P>::block_on::ha9b21d11623ba87c
  23:   0x47efa8 - tokio_timer::timer::handle::with_default::h49052d56ddbe1634
  24:   0x461c04 - std::thread::local::LocalKey<T>::with::h15a5d3e5058f8296
  25:   0x4856e4 - scoped_tls::ScopedKey<T>::set::ha239ba9e873b9553
  26:   0x468f04 - tokio_core::reactor::Core::run::he161dc1ccad6b1bb
  27:   0x47bce4 - librespot::main::h6424af6f8ac98335
  28:   0x47f538 - std::rt::lang_start::{{closure}}::h20fd6404e8f8e33a
  29:   0x88e8e4 - std::rt::lang_start_internal::{{closure}}::he71ca971345dcdbf
                       at src/libstd/rt.rs:52
  30:   0x88e8e4 - std::panicking::try::do_call::h3ebcd0c1fd722d55
                       at src/libstd/panicking.rs:297
  31:   0x88e8e4 - std::panicking::try::he6a0b75af361a6ec
                       at src/libstd/panicking.rs:274
  32:   0x88e8e4 - std::panic::catch_unwind::h2fbf955b2ece72b7
                       at src/libstd/panic.rs:394
  33:   0x88e8e4 - std::rt::lang_start_internal::ha55d91cd07438bce
                       at src/libstd/rt.rs:51
  34:   0x47cc78 - main
  35: 0x76c82718 - __libc_start_main
                       at /build/glibc-FUvrFr/glibc-2.28/csu/libc-start.c:308
```

**Comment by tysonnorris** [comment]
I got mine to start playing by terminating some aplay service that was installed by the adafruit speaker bonnet setup installed (see https://learn.adafruit.com/adafruit-speaker-bonnet-for-raspberry-pi/raspberry-pi-usage)
After stopping aplay service (was supposed to help with popping on open/close of audio device?), librespot works fine with it.

**Comment by Malvineous** [comment]
Is this still happening?  There were some bugs on Spotify's end late last year causing these issues but I haven't seen them for a few months now so I'm wondering if this problem has now been resolved after Spotify fixed their servers.

**Comment by asirinelli** [comment]
You are correct @Malvineous. I have not encountered this errors for the past few months.
