### ISSUE TITLE
Crash after a while

### ISSUE THREAD

**Issue by ngravic** [librespot-org/librespot#468]
Hello there, I'm having this problem since a few days, after an update. I have:
- RPi 3B
- Raspbian 9.11
- librespot (raspotify v0.14.0) 3672214 (2020-01-30). Built on 2020-02-16. Build ID: 7pZDdYUK

Logs:
```
Apr 20 19:11:37 raspberrypi librespot[848]: thread '<unnamed>' panicked at 'Vorbis error: OggError(ReadError(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }))', src/libcore/result.rs:1188:5
Apr 20 19:11:37 raspberrypi librespot[848]: stack backtrace:
Apr 20 19:11:37 raspberrypi librespot[848]:    0:   0x91b3a4 - backtrace::backtrace::libunwind::trace::hb1e9954dcc6e7c1f
Apr 20 19:11:37 raspberrypi librespot[848]:                        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
Apr 20 19:11:37 raspberrypi librespot[848]:    1:   0x91b3a4 - backtrace::backtrace::trace_unsynchronized::h1b198a73034a9734
Apr 20 19:11:37 raspberrypi librespot[848]:                        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
Apr 20 19:11:37 raspberrypi librespot[848]:    2:   0x91b3a4 - std::sys_common::backtrace::_print_fmt::hf691518b63d0b79d
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/sys_common/backtrace.rs:84
Apr 20 19:11:37 raspberrypi librespot[848]:    3:   0x91b3a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he6a16924c7e1913e
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/sys_common/backtrace.rs:61
Apr 20 19:11:37 raspberrypi librespot[848]:    4:   0x93dca4 - core::fmt::write::hc426988e4c4119a8
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libcore/fmt/mod.rs:1025
Apr 20 19:11:37 raspberrypi librespot[848]:    5:   0x915ff0 - std::io::Write::write_fmt::h34e90dde595ba7cd
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/io/mod.rs:1426
Apr 20 19:11:37 raspberrypi librespot[848]:    6:   0x91d954 - std::sys_common::backtrace::_print::h406863a8800396cd
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/sys_common/backtrace.rs:65
Apr 20 19:11:37 raspberrypi librespot[848]:    7:   0x91d954 - std::sys_common::backtrace::print::hec570bc9fdd6a536
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/sys_common/backtrace.rs:50
Apr 20 19:11:37 raspberrypi librespot[848]:    8:   0x91d954 - std::panicking::default_hook::{{closure}}::hf187be78db8e291b
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/panicking.rs:193
Apr 20 19:11:37 raspberrypi librespot[848]:    9:   0x91d5b4 - std::panicking::default_hook::h9634e45fc0d61ba6
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/panicking.rs:210
Apr 20 19:11:37 raspberrypi librespot[848]:   10:   0x91e030 - std::panicking::rust_panic_with_hook::h35923fdea5783220
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/panicking.rs:471
Apr 20 19:11:37 raspberrypi librespot[848]:   11:   0x91dc48 - rust_begin_unwind
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/panicking.rs:375
Apr 20 19:11:37 raspberrypi librespot[848]:   12:   0x939ac0 - core::panicking::panic_fmt::hd74e307162bc16e5
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libcore/panicking.rs:84
Apr 20 19:11:37 raspberrypi librespot[848]:   13:   0x939bac - core::result::unwrap_failed::h36f73057b442c0eb
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libcore/result.rs:1188
Apr 20 19:11:37 raspberrypi librespot[848]:   14:   0x4e5638 - librespot_playback::player::PlayerInternal::run::hc0a120cd06b334c0
Apr 20 19:11:37 raspberrypi librespot[848]:   15:   0x43e3a4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c6871de616d8893
Apr 20 19:11:37 raspberrypi librespot[848]:   16:   0x43978c - std::panicking::try::do_call::hac2a3db38490f7c2
Apr 20 19:11:37 raspberrypi librespot[848]:   17:   0x925220 - __rust_maybe_catch_panic
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libpanic_unwind/lib.rs:78
Apr 20 19:11:37 raspberrypi librespot[848]:   18:   0x45a200 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h39f2cbdbe410812b
Apr 20 19:11:37 raspberrypi librespot[848]:   19:   0x90e790 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hc0d20dd2593d70b4
Apr 20 19:11:37 raspberrypi librespot[848]:                        at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
Apr 20 19:11:37 raspberrypi librespot[848]:   20:   0x9243e4 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h81836ca2a42ca881
Apr 20 19:11:37 raspberrypi librespot[848]:                        at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
Apr 20 19:11:37 raspberrypi librespot[848]:   21:   0x9243e4 - std::sys_common::thread::start_thread::hdbf450a6e252329e
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/sys_common/thread.rs:13
Apr 20 19:11:37 raspberrypi librespot[848]:   22:   0x9243e4 - std::sys::unix::thread::Thread::new::thread_start::h5823a94baad158fb
Apr 20 19:11:37 raspberrypi librespot[848]:                        at src/libstd/sys/unix/thread.rs:80
```

It seems like a codec error, but I don't know where to start. I haven't found anything related

**Comment by ashthespy** [comment]
Does it happen for all tracks? If not, could you share the URI of the particular track?

**Comment by ngravic** [comment]
Yes, I've tried with several tracks, and it crashed with all of them

**Comment by ngravic** [comment]
I've tried changing the quality (320,160,96kbps) without success

**Comment by ngravic** [comment]
It seems that the problem was because the device had run out of disk space. I deleted some files, restarted the service, and everything worked again

**Comment by marnanel** [comment]
I suspect this may have been a duplicate of issue 265.
