### ISSUE TITLE
zeroconf device shows but crashes when try to connect

### ISSUE THREAD

**Issue by jgabriel98** [librespot-org/librespot#509]
when i run librespot with the following command:
`librespot --name 'Smarthome' --backend pipe --bitrate 160 --disable-audio-cache --enable-volume-normalisation --linear-volume --initial-volume=100 --device /tmp/snapfifo --verbose`

i get this error:
**Probably the relevant log part**:
```
[2020-07-25T23:08:57Z DEBUG librespot_connect::discovery] Zeroconf server listening on 0.0.0.0:38525
[2020-07-25T23:09:03Z DEBUG librespot_connect::discovery] Post "/" {}
[2020-07-25T23:09:04Z INFO  librespot_core::session] Connecting to AP "guc3-accesspoint-b-fqrg.ap.spotify.com:4070"
[2020-07-25T23:09:04Z INFO  librespot_core::session] Authenticated as "jgabriel98" !
[2020-07-25T23:09:04Z DEBUG librespot_core::session] new Session[0]
[2020-07-25T23:09:04Z DEBUG librespot_connect::spirc] new Spirc[0]
[2020-07-25T23:09:04Z DEBUG librespot_core::mercury] new MercuryManager
[2020-07-25T23:09:04Z DEBUG librespot_playback::player] new Player[0]
[2020-07-25T23:09:04Z DEBUG librespot_connect::spirc] linear volume: 65535
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', playback/src/audio_backend/pipe.rs:12:24
```

**the full log with backtrace**:
```
[2020-07-25T23:08:57Z INFO  librespot] librespot UNKNOWN (UNKNOWN). Built on 2020-07-25. Build ID: LeIssbEx
[2020-07-25T23:08:57Z DEBUG librespot_connect::discovery] Zeroconf server listening on 0.0.0.0:38525
[2020-07-25T23:09:03Z DEBUG librespot_connect::discovery] Post "/" {}
[2020-07-25T23:09:04Z INFO  librespot_core::session] Connecting to AP "guc3-accesspoint-b-fqrg.ap.spotify.com:4070"
[2020-07-25T23:09:04Z INFO  librespot_core::session] Authenticated as "jgabriel98" !
[2020-07-25T23:09:04Z DEBUG librespot_core::session] new Session[0]
[2020-07-25T23:09:04Z DEBUG librespot_connect::spirc] new Spirc[0]
[2020-07-25T23:09:04Z DEBUG librespot_core::mercury] new MercuryManager
[2020-07-25T23:09:04Z DEBUG librespot_playback::player] new Player[0]
[2020-07-25T23:09:04Z DEBUG librespot_connect::spirc] linear volume: 65535
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', playback/src/audio_backend/pipe.rs:12:24
[2020-07-25T23:09:04Z DEBUG librespot_core::session] Session[0] strong=3 weak=2
stack backtrace:
[2020-07-25T23:09:04Z INFO  librespot_core::session] Country: "BR"
[2020-07-25T23:09:05Z DEBUG librespot_core::mercury] unknown subscription uri=hm://remote/user/jgabriel98/
[2020-07-25T23:09:05Z DEBUG librespot_core::mercury] subscribed uri=hm://remote/user/jgabriel98/ count=0
   0:   0x93a7f4 - backtrace::backtrace::libunwind::trace::h42e1dbc12834dc55
                       at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:   0x93a7f4 - backtrace::backtrace::trace_unsynchronized::h158176f5f0421f59
                       at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:   0x93a7f4 - std::sys_common::backtrace::_print_fmt::h45f710eeea48abbc
                       at src/libstd/sys_common/backtrace.rs:78
   3:   0x93a7f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha321f8aaf88e66cb
                       at src/libstd/sys_common/backtrace.rs:59
   4:   0x95def4 - core::fmt::write::h8010a13f42cc6ad4
                       at src/libcore/fmt/mod.rs:1076
   5:   0x933f98 - std::io::Write::write_fmt::h54bacacaef7d9896
                       at src/libstd/io/mod.rs:1537
   6:   0x93d088 - std::sys_common::backtrace::_print::h10fb63f1b52679e7
                       at src/libstd/sys_common/backtrace.rs:62
   7:   0x93d088 - std::sys_common::backtrace::print::h27bc45a9400bc7e5
                       at src/libstd/sys_common/backtrace.rs:49
   8:   0x93d088 - std::panicking::default_hook::{{closure}}::h10afbc2a3e05e9be
                       at src/libstd/panicking.rs:198
   9:   0x93cd54 - std::panicking::default_hook::h3a74519daf0f6288
                       at src/libstd/panicking.rs:218
  10:   0x93d740 - std::panicking::rust_panic_with_hook::h88381d57025ef851
                       at src/libstd/panicking.rs:486
  11:   0x93d35c - rust_begin_unwind
                       at src/libstd/panicking.rs:388
  12:   0x95b72c - core::panicking::panic_fmt::h23a69cbedf3d3798
                       at src/libcore/panicking.rs:101
  13:   0x95b584 - core::option::expect_none_failed::h8b89bcdbf5294b10
                       at src/libcore/option.rs:1272
  14:   0x5eadb8 - <librespot_playback::audio_backend::pipe::StdoutSink as librespot_playback::audio_backend::Open>::open::h4a43d34493df0708
  15:   0x5d87bc - librespot_playback::audio_backend::mk_sink::hacffab71950f0eba
  16:   0x52d7c4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7d5f4342f37d1bef
  17:   0x54440c - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf7808d86c391026e
  18:   0x943a90 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hfff86e20b994df58
                       at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
  19:   0x943a90 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he611472e18ee6497
                       at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
  20:   0x943a90 - std::sys::unix::thread::Thread::new::thread_start::hd0a4cd3b661718b3
                       at src/libstd/sys/unix/thread.rs:87
[2020-07-25T23:09:05Z DEBUG librespot_connect::spirc] kMessageTypeLoad "iPhone de joao gabriel" 1107330bc96183334b16572f1e777e7c0e45ae94 138195680 1595718544963 kPlayStatusPause
[2020-07-25T23:09:05Z DEBUG librespot_connect::spirc] State: context_uri: "spotify:user:jgabriel98:collection" index: 6 position_ms: 63253 status: kPlayStatusPause position_measured_at: 1595718545457 context_description: "" shuffle: false repeat: false playing_from_fallback: true row: 0 playing_track_index: 6 track {gid: "\362P\214\372 \303Cz\2670bJ+\205(D"} track {gid: "L\274\023#JGB\324\242\325\327\024\244\363\320\252"} track {gid: "l\276\216\032T\250K6\222e\010=\355\234\350\017"} track {gid: "Ci\3137`\030K\027\213dK\336\205\343s\245"} track {gid: "\340\353\264\326h\371G\351\271>\266\001 JF\243"} track {gid: "K\345\365\344!DJ\226\260h`{\316\356\027\374"} track {gid: "\016\264\265\202`\266G~\206\232\2065\205J\265\r"} track {gid: "\017U\353w\270YO\274\253\217[\305\261\r\372n"} track {gid: "B14\241\223EK\251\256,\251\212}\325>\345"} track {gid: "\205\tn\013^\360J\020\235%c\334}>t\177"} track {gid: "\306x6\254\233\221G\323\276F\256\253J\013\274\302"} track {gid: "\244W\253\251\212\226F0\243\323\322b\377F\244\252"} track {gid: "\334\220Yh\335vM\334\264r@z\3211\276b"} track {gid: "`\251\203\037\000'@\274\271[8\356\234H\233\005"} track {gid: "\034\253\343d2\377K(\263\0045\373>3\2177"} track {gid: "\007\202;/\311PI\234\277\002IQ(\202\360f"} track {gid: "DYO3\324\204B\224\260\232\205p\272\266\032\020"} track {gid: "\014J\203c\\7C\027\260\364\203\327\324#\027\254"} track {gid: "\254\360\252\233{\215@\262\243{N\004\033H\361`"} track {gid: "\221Z\333I\336dL\311\202\331OSw\312\354\257"} track {gid: "0\237v\314\306\230G\325\267\301\254vI\304N\022"} track {gid: "\334\247aIR\350J\331\236\nq \225h{\262"} track {gid: "}\001\313\211\005\370J|\224~ISyUML"} track {gid: "a\203\251\373\025\374G(\241=d=\304\213\246\264"} track {gid: "\371\344x-[\325G\223\241{\214\3755\346\t\271"} track {gid: "wk\2363:\320L\374\246\016\326\350\351\234-\227"} track {gid: "?\322\032\360f\022J\267\260\034o\301\334\336:\365"} track {gid: "\301\020\\-\221\352@t\236r\021\277\000A\244\245"} track {gid: "\250\360U\243\376DEg\221\013\376\330\354B\213\242"} track {gid: "\206\374cu\252\330G\377\210\246e>Hp\353'"} track {gid: "`\005\223\361C\244Do\244+\021T\027\263\251A"} track {gid: "N\264c\372\301\030@\350\203u\307\264\205\354Q("} track {gid: "\262\243)\325\224\272M\377\204\310\246\246I\257=\316"} track {gid: "\005\3425L\231XJ\323\213\351\253\213\252\355S,"} track {gid: "Gt\357\270\325\224E>\2068:\236\360M\253\332"} track {gid: "\263.q\224l\220BM\245\272\345\220\323\260\"Q"} track {gid: "\314\242\3468\332zH\363\254\226\212 \314\211f\200"} track {gid: "\204D\352\n\261\024J\227\217\361\376\315Ep\207\222"} track {gid: "\362d:2$\362@\337\223\351j\264f]l\000"} track {gid: "\022\342%\370-aIt\276\321\200\211\336\342U\232"} track {gid: "$Da:\005@E\374\200\331).\370JZ\215"} track {gid: "\355\221\"\346\205\006Nr\262vW\302\377C}\010"} track {gid: "\337JC\346\001\032J\345\232|m \267\235\301o"} track {gid: "\362\372\336)\314\354F\003\255]\022\001T\032\3741"} track {gid: "n#\240\216\227\255K_\216\\\374@~\021j-"} track {gid: "\371\205\356X\370^@}\242]\217\023\307[\265t"} track {gid: "\353t\345f~\337D/\217H\262\361,\2172j"} track {gid: "\332v\007\253=\240G\252\227\250\364w\372\354\263\271"} track {gid: "\257rl\037<\235I\373\241\243\332\3371\212\372\210"} track {gid: "5\341v\261\320\375HH\244\347\233\314a\223\332\340"} track {gid: "O\200\022\220\325+F\373\226\276D\031r\322t\310"} track {gid: "\324\301\203\273V\235M\314\215$\275\316\267\327\r\037"} track {gid: " \034\244\361\016\330I\343\246\033d\264(\233\016^"} track {gid: "\311\362\377\224\320\\L\220\247\360\374\374\204%\334\231"} track {gid: "\014\225\347\236HLAq\251\036\354\30786]E"} track {gid: "\363]\016'\034=A3\271\037/\345\203\220K\314"} track {gid: "\362\316\314i\322\214C0\217S\370ET\256\022\263"} track {gid: "Z\364z\240\325\035B\312\246\362B\013\253G\215\256"} track {gid: "\032\207\340\221\177\371L\001\243:V\353\013\020\225\205"} track {gid: "\007d_\262\250\346I\240\250c\036\265\274w\216\272"} track {gid: "7x\270\225{vD\207\231X\270\345l\313)\335"} track {gid: "\243\034\342\216}\250AK\220\315sfa\017``"} track {gid: "\334\374\025\261,\216F\357\2568TyRo`\274"} track {gid: "\240\034\346\013\247\330E\337\250U\214\247\271IY\375"} track {gid: ".\272\372\017~7Dg\201\303 \316\2521+$"} track {gid: "\273\310P\351'\210IH\243t\271{\326\2677\231"} track {gid: ">Z;\020\225\002O\251\2236\017\000\233It\227"} track {gid: "J\347\332\2679\017NJ\203\013\206\310\253%E!"} track {gid: "\223\314\347i\271(F\177\250\035\nL\320\205\374\005"} track {gid: "\240\000\351\245'\220E\322\204\277\307L1\t\303\017"} track {gid: "\374\267n4/GF\217\245<\350k\350\3334!"} track {gid: "Y\017\035~\330\225Gh\242\202\376\250\014!\221\262"} track {gid: "\216\203x4\230\245K\324\236\027\272j\037\3233E"} track {gid: "\244\2508\n\334\013L\332\246Y\200p>>_\312"} track {gid: "XE\211\345\251&N\240\254\330\305\007_\013\274]"} track {gid: "\361p\344z\276\313@\033\240\325\307\364u\367l\263"} track {gid: "\377\231\r\257n\215H\177\233\261\024\017\331Z\302\257"} track {gid: "\370 \177\004\272\030L\302\201g)\027\205V\006\021"} track {gid: "tt\272\315\356YB\240\227\270\334\335Ttf\270"} track {gid: "\355\244\224\022\200KDL\242K\006Q\342-<\025"} track {gid: "S\234E=JDO\311\265+\232\365\"[n\323"} track {gid: "2\0001\273\253\243Ct\211{\241)O\017\274\004"} track {gid: "\244\024\007\325\246\310@\204\237\367\267\367qn:\316"} track {gid: "\021\365\032\270\316\264A\t\203\212Gs\323\\w\206"} track {gid: "\261\225\335X\254.OO\231\024\336\354\337\002\276\200"} track {gid: "\221\206\225-%\231F\027\277\202\201\254[\013s\022"} track {gid: "\345\324\254!hTC(\205\032\244\205\234\232\013c"}
[2020-07-25T23:09:05Z DEBUG librespot_connect::spirc] Frame has 87 tracks
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")', playback/src/player.rs:257:9
stack backtrace:
   0:   0x93a7f4 - backtrace::backtrace::libunwind::trace::h42e1dbc12834dc55
                       at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:   0x93a7f4 - backtrace::backtrace::trace_unsynchronized::h158176f5f0421f59
                       at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:   0x93a7f4 - std::sys_common::backtrace::_print_fmt::h45f710eeea48abbc
                       at src/libstd/sys_common/backtrace.rs:78
   3:   0x93a7f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha321f8aaf88e66cb
                       at src/libstd/sys_common/backtrace.rs:59
   4:   0x95def4 - core::fmt::write::h8010a13f42cc6ad4
                       at src/libcore/fmt/mod.rs:1076
   5:   0x933f98 - std::io::Write::write_fmt::h54bacacaef7d9896
                       at src/libstd/io/mod.rs:1537
   6:   0x93d088 - std::sys_common::backtrace::_print::h10fb63f1b52679e7
                       at src/libstd/sys_common/backtrace.rs:62
   7:   0x93d088 - std::sys_common::backtrace::print::h27bc45a9400bc7e5
                       at src/libstd/sys_common/backtrace.rs:49
   8:   0x93d088 - std::panicking::default_hook::{{closure}}::h10afbc2a3e05e9be
                       at src/libstd/panicking.rs:198
   9:   0x93cd54 - std::panicking::default_hook::h3a74519daf0f6288
                       at src/libstd/panicking.rs:218
  10:   0x93d740 - std::panicking::rust_panic_with_hook::h88381d57025ef851
                       at src/libstd/panicking.rs:486
  11:   0x93d35c - rust_begin_unwind
                       at src/libstd/panicking.rs:388
  12:   0x95b72c - core::panicking::panic_fmt::h23a69cbedf3d3798
                       at src/libcore/panicking.rs:101
  13:   0x95b584 - core::option::expect_none_failed::h8b89bcdbf5294b10
                       at src/libcore/option.rs:1272
  14:   0x5c6934 - librespot_playback::player::Player::load::h93c6876eb5110c64
  15:   0x591380 - librespot_connect::spirc::SpircTask::load_track::hce655767ea026238
  16:   0x58e2f8 - <librespot_connect::spirc::SpircTask as futures::future::Future>::poll::hd6d78d05cae3453f
  17:   0x53f880 - <librespot::Main as futures::future::Future>::poll::h906f28cde4de809c
  18:   0x545fe8 - futures::task_impl::std::set::h4470ffcd3cbcc19d
  19:   0x546240 - futures::task_impl::std::set::h569afefb1b66a234
  20:   0x5289dc - std::thread::local::LocalKey<T>::with::hcffb5297a18daeb4
  21:   0x525cac - tokio_current_thread::Entered<P>::block_on::h7199e21496b6ddc6
  22:   0x54537c - tokio_timer::timer::handle::with_default::haf181607b54c3a6a
  23:   0x528890 - std::thread::local::LocalKey<T>::with::hbb036fdd624aa00e
  24:   0x524484 - scoped_tls::ScopedKey<T>::set::hcb256e77294bc758
  25:   0x52fef8 - tokio_core::reactor::Core::run::h1a7af87a8bb728cd
  26:   0x542198 - librespot::main::h6cf4d8904ebb54d3
  27:   0x530a74 - std::rt::lang_start::{{closure}}::hb5cdb6969ecf1904
  28:   0x93dae8 - std::rt::lang_start_internal::{{closure}}::h7caec43ed49da58e
                       at src/libstd/rt.rs:52
  29:   0x93dae8 - std::panicking::try::do_call::ha509877638d5cafc
                       at src/libstd/panicking.rs:297
  30:   0x93dae8 - std::panicking::try::hf5441dc83cef8896
                       at src/libstd/panicking.rs:274
  31:   0x93dae8 - std::panic::catch_unwind::hc366a1b13107a6fa
                       at src/libstd/panic.rs:394
  32:   0x93dae8 - std::rt::lang_start_internal::h30c213b4de8d3c63
                       at src/libstd/rt.rs:51
  33:   0x5431f0 - main
  34: 0xb6d2f718 - __libc_start_main
                       at /build/glibc-FUvrFr/glibc-2.28/csu/libc-start.c:308
[2020-07-25T23:09:05Z DEBUG librespot_connect::spirc] drop Spirc[0]
[2020-07-25T23:09:05Z DEBUG librespot_playback::player] Shutting down player thread ...
[2020-07-25T23:09:05Z ERROR librespot_playback::player] Player thread panicked!
[2020-07-25T23:09:05Z DEBUG librespot_core::session] drop Session[0]
[2020-07-25T23:09:05Z DEBUG librespot_core::mercury] drop MercuryManager
[2020-07-25T23:09:05Z DEBUG librespot_core::session] drop Dispatch
```

the librespot just stopped working for no obvious reason, before i could connect with n problems, but after two days this new behavior came and wont fix even if i resintall or recompile it.

Running on a raspberry pi 4, with raspbery OS.

**Comment by ashthespy** [comment]
This hasn't got anything to do with zeroconf :-) 
The error seems to stem from the your pipe `/tmp/snapfifo` not being accessible (the "Permission denied" error. ) due to permissions. Try checking if your binary has the read/write permissions to the pipe. 
You could confirm by piping to `/dev/null` instead and checking everything works (minus the sound of course)

**Comment by jgabriel98** [comment]
as told by @ashthespy , the problem was with pipe.

Found out that in some cases _shairport-sync_ was creating the pipe before _snapcast snapserver_, and it seems that shairport-sync pipe is not very friendly.

manually starting snapserver before shairport-sync solved the issue.

i will try to make the snapserver.service and shairport-sync.service services coordinate themselves, and update here any discoveries
