### ISSUE TITLE
Crash when starting up with username

### ISSUE THREAD

**Issue by hbbtstar** [librespot-org/librespot#838]
Hey all!

I'm attempting to use librespot 0.2.0 (version string on startup is librespot 0.2.0 UNKNOWN (Built on 2021-08-28, Build ID: cETMHgxg)) and it's crashing on startup after authenticating: the stack trace is reproduced below with my username omitted.

```
Aug 29 02:04:30 localhost.localdomain librespot[16737]: [2021-08-29T02:04:30Z INFO  librespot_core::session] Connecting to AP "guc3-accesspoint-a-852g.ap.spotify.com:4070"
Aug 29 02:04:30 localhost.localdomain librespot[16737]: [2021-08-29T02:04:30Z INFO  librespot_core::session] Authenticated as "username" !
Aug 29 02:04:30 localhost.localdomain librespot[16737]: [2021-08-29T02:04:30Z INFO  librespot_core::session] Country: "US"
Aug 29 02:04:30 localhost.localdomain librespot[16737]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "Invalid argument"', src/libcore/result.rs:1188:5
Aug 29 02:04:30 localhost.localdomain librespot[16737]: stack backtrace:
Aug 29 02:04:30 localhost.localdomain librespot[16737]:    0:       0x5571950ef4 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:    1:       0x557196c318 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:    2:       0x557194f004 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:    3:       0x5571951920 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:    4:       0x5571951630 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:    5:       0x5571951fc4 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:    6:       0x5571951bf0 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:    7:       0x557196ffac - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:    8:       0x557196bb48 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:    9:       0x55715e434c - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   10:       0x55715e3c34 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   11:       0x55715dd0a8 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   12:       0x55715c79d4 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   13:       0x55715bea1c - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   14:       0x55715d2b60 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   15:       0x557151b41c - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   16:       0x557151bc34 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   17:       0x5571956cf0 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   18:       0x55715354b0 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   19:       0x557193d71c - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   20:       0x557194fefc - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   21:       0x5571945f84 - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   22:       0x7f911d24fc - start_thread
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   23:       0x7f9110767c - <unknown>
Aug 29 02:04:30 localhost.localdomain librespot[16737]:   24:                0x0 - <unknown>
```

I think it's something getting called in the session.rs file, since when I run the command without a username and password it doesn't crash and runs just fine.

I'm going to investigate more this week (including building an unstripped version of the library to demystify those stack traces) but I thought I'd open the ticket now to see if anybody had any initial directions to point me in. Thanks!

**Comment by roderickvd** [comment]
Not at this point, the full stack trace of a debug build would be helpful.

**Comment by hbbtstar** [comment]
so I think actually the crash was on attempting to play a song, not on startup: I got this stack trace when I started up with a debug build:

```
[2021-08-29T13:59:08Z INFO  librespot] librespot 0.2.0 7f6386a (Built on 2021-08-29, Build ID: feELcxye)
[2021-08-29T13:59:08Z INFO  librespot_core::session] Connecting to AP "guc3-accesspoint-a-2mrg.ap.spotify.com:4070"
[2021-08-29T13:59:09Z INFO  librespot_core::session] Authenticated as "username" !
[2021-08-29T13:59:09Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0)
[2021-08-29T13:59:09Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
[2021-08-29T13:59:09Z INFO  librespot_playback::audio_backend::rodio] Using Rodio sink with format S16 and cpal host: ALSA
[2021-08-29T13:59:09Z INFO  librespot_playback::audio_backend::rodio] Using audio device: default
[2021-08-29T13:59:09Z INFO  librespot_core::session] Country: "US"
thread 'cpal_alsa_out' panicked at 'get_htstamp `timespec { tv_sec: 81547, tv_nsec: 64055286 }` was earlier than get_trigger_htstamp `timespec { tv_sec: 81547, tv_nsec: 128471690 }`', /home/mycroft/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.4/src/host/alsa/mod.rs:860:17
stack backtrace:
   0:       0x559366bcec - std::backtrace_rs::backtrace::libunwind::trace::hecc4fb3dc5a91037
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:       0x559366bcec - std::backtrace_rs::backtrace::trace_unsynchronized::h9f238248263b1f81
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:       0x559366bcec - std::sys_common::backtrace::_print_fmt::hae64a821d41b4b14
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:       0x559366bcec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha504e6c6649c19e9
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:       0x559368d1f8 - core::fmt::write::h7c914d42a8e99f57
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:       0x55936659dc - std::io::Write::write_fmt::hb2f3ddc6101ed08d
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:       0x559366de68 - std::sys_common::backtrace::_print::h1e31b5a4bc5a5719
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:       0x559366de68 - std::sys_common::backtrace::print::h3453f1f2e887cb14
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:       0x559366de68 - std::panicking::default_hook::{{closure}}::hd0cacc29652b13c4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:       0x559366d980 - std::panicking::default_hook::h0d7faf1abbe91b0d
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:       0x559366e4c0 - std::panicking::rust_panic_with_hook::he3ac366c10fca72f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:       0x559366dff8 - std::panicking::begin_panic_handler::{{closure}}::h1a8dd2d97f4ecde7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:       0x559366c1ac - std::sys_common::backtrace::__rust_end_short_backtrace::hace36748d5046612
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:       0x559366df60 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:       0x5592c7ffec - std::panicking::begin_panic_fmt::hc9ea67dbc9040e2b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
  15:       0x5592fdd654 - cpal::host::alsa::stream_timestamp::h4a16e6b185fe0661
                               at /home/mycroft/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.4/src/host/alsa/mod.rs:860:17
  16:       0x5592fdd06c - cpal::host::alsa::process_output::hed1f28b862c5a8f3
                               at /home/mycroft/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.4/src/host/alsa/mod.rs:810:24
  17:       0x5592fdc578 - cpal::host::alsa::output_stream_worker::h621a8c78956722c0
                               at /home/mycroft/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.4/src/host/alsa/mod.rs:638:27
  18:       0x5592f418dc - cpal::host::alsa::Stream::new_output::{{closure}}::h9741774d23cad595
                               at /home/mycroft/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.4/src/host/alsa/mod.rs:938:17
  19:       0x5592f4e388 - std::sys_common::backtrace::__rust_begin_short_backtrace::h83428b4c53ea1cbf
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  20:       0x5592f5ae18 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h1814c6f26b9338ae
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:481:17
  21:       0x5592f53e80 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4258730de4e6c737
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  22:       0x5592f5eccc - std::panicking::try::do_call::hd0343b7c4aded00c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  23:       0x5592f60d58 - __rust_try
  24:       0x5592f5ebe4 - std::panicking::try::hf2234f9e98a64492
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  25:       0x5592f5453c - std::panic::catch_unwind::hf9efe0b2c4eb7eba
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  26:       0x5592f5a7d4 - std::thread::Builder::spawn_unchecked::{{closure}}::h04ba409625f632a0
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:480:30
  27:       0x5592f481cc - core::ops::function::FnOnce::call_once{{vtable.shim}}::he3fec9295049ce6f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  28:       0x5593673694 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa4d3b5ddd6d9869
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  29:       0x5593673694 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0aef23fe7df0118e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  30:       0x5593673694 - std::sys::unix::thread::Thread::new::thread_start::hdfee29d92645d1f2
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys/unix/thread.rs:71:17
  31:       0x7f8b4664fc - start_thread
  32:       0x7f8b2fe67c - <unknown>
  33:                0x0 - <unknown>
```

I rebooted the dev kit and it seemed to clear out whatever old stream was stuck in memory (I'm guessing, since the error appears to be related to bad timestamps) has been resolved! Closing this out as everything is working correctly now

**Comment by roderickvd** [comment]
Thanks for the feedback, glad to hear it's working.
