### ISSUE TITLE
[dev] USB Audio card not detected by librespot with ALSA

### ISSUE THREAD

**Issue by davidlb** [librespot-org/librespot#839]
librespot 0.2 was running fine with my USB Audio card and now, I wanted to give a try to the dev branch, my USB card is not usable/detected. Any idea or what I could do for debugging?

Here is the result of:
```
./librespot --device ?
[2021-08-30T13:53:42Z INFO  librespot] librespot 0.2.0 7f6386a (Built on 2021-08-30, Build ID: wPhhBS6s)
Listing available Alsa outputs:
pcm devices:
sysdefault:CARD=b1
        bcm2835 HDMI 1, bcm2835 HDMI 1
        Default Audio Device

dmix:CARD=b1,DEV=0
        bcm2835 HDMI 1, bcm2835 HDMI 1
        Direct sample mixing device

dsnoop:CARD=b1,DEV=0
        bcm2835 HDMI 1, bcm2835 HDMI 1
        Direct sample snooping device

hw:CARD=b1,DEV=0
        bcm2835 HDMI 1, bcm2835 HDMI 1
        Direct hardware device without any conversions

plughw:CARD=b1,DEV=0
        bcm2835 HDMI 1, bcm2835 HDMI 1
        Hardware device with all software conversions

sysdefault:CARD=Headphones
        bcm2835 Headphones, bcm2835 Headphones
        Default Audio Device

dmix:CARD=Headphones,DEV=0
        bcm2835 Headphones, bcm2835 Headphones
        Direct sample mixing device

dsnoop:CARD=Headphones,DEV=0
        bcm2835 Headphones, bcm2835 Headphones
        Direct sample snooping device

hw:CARD=Headphones,DEV=0
        bcm2835 Headphones, bcm2835 Headphones
        Direct hardware device without any conversions

plughw:CARD=Headphones,DEV=0
        bcm2835 Headphones, bcm2835 Headphones
        Hardware device with all software conversions

ctl devices:
hwdep devices:
```
```
aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
sysdefault:CARD=b1
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Default Audio Device
dmix:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct sample mixing device
dsnoop:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct sample snooping device
hw:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct hardware device without any conversions
plughw:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Hardware device with all software conversions
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
dmix:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample mixing device
dsnoop:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample snooping device
hw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct hardware device without any conversions
plughw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Hardware device with all software conversions
**sysdefault:CARD=Device
    USB Advanced Audio Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    Front speakers
surround21:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    Direct sample mixing device
dsnoop:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    Direct sample snooping device
hw:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    Direct hardware device without any conversions
plughw:CARD=Device,DEV=0
    USB Advanced Audio Device, USB Audio
    Hardware device with all software conversions**
```

Thanks for your help!

**Comment by davidlb** [comment]
Wait, it was not detected with librespot 0.2 neither, I probably have a problem in my setup.

**Comment by davidlb** [comment]
Sorry, finally it's a bug. I cannot run librespot from the dev branch:

**librespot 0.2**
```
bin/librespot_0.2.0 --device hw:2 --backend alsa --mixer softvol --mixer-name Speaker --mixer-card=hw:2 --autoplay -c /tmp -v
[2021-08-30T15:30:48Z INFO  librespot] librespot 0.2.0 fce91f4 (Built on 2021-05-10, Build ID: oam0bCN4)
[2021-08-30T15:30:48Z DEBUG librespot_connect::discovery] Zeroconf server listening on 0.0.0.0:35225
[2021-08-30T15:30:48Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-a-qgm7.ap.spotify.com:4070"
[2021-08-30T15:30:48Z INFO  librespot_core::session] Authenticated as "vr49fptlr7ho4awkb4hzxvz3v" !
[2021-08-30T15:30:48Z DEBUG librespot_core::session] new Session[0]
[2021-08-30T15:30:48Z DEBUG librespot_connect::spirc] new Spirc[0]
[2021-08-30T15:30:48Z DEBUG librespot_connect::spirc] canonical_username: vr49fptlr7ho4awkb4hzxvz3v
[2021-08-30T15:30:48Z DEBUG librespot_core::mercury] new MercuryManager
[2021-08-30T15:30:48Z DEBUG librespot_playback::player] new Player[0]
[2021-08-30T15:30:48Z INFO  librespot_playback::audio_backend::alsa] Using Alsa sink with format: S16
[2021-08-30T15:30:48Z DEBUG librespot_playback::player] command=AddEventSender
[2021-08-30T15:30:48Z DEBUG librespot_connect::spirc] input volume:58981 to mixer: 32850
[2021-08-30T15:30:48Z DEBUG librespot_playback::player] command=VolumeSet(58981)
[2021-08-30T15:30:48Z DEBUG librespot_core::session] Session[0] strong=3 weak=2
[2021-08-30T15:30:48Z INFO  librespot_core::session] Country: "FR"
[2021-08-30T15:30:48Z DEBUG librespot_core::mercury] subscribed uri=hm://remote/user/vr49fptlr7ho4awkb4hzxvz3v/ count=0
[2021-08-30T15:30:48Z DEBUG librespot_connect::spirc] kMessageTypeNotify "Bbox Miami" 45a63037bfd77080e2a773449f3d3bf4181dfffb 397360521 1630337448594 kPlayStatusStop
```
**librespot dev version**
```
bin/librespot_0.2.1 --device hw:2 --backend alsa --mixer softvol --mixer-name Speaker --mixer-card=hw:2 --autoplay -c /tmp -v
[2021-08-30T15:30:54Z INFO  librespot] librespot 0.2.0 7f6386a (Built on 2021-08-30, Build ID: wPhhBS6s)
thread 'main' panicked at 'Invalid mixer', src/main.rs:458:52
stack backtrace:
   0:   0x8ecdf0 - std::backtrace_rs::backtrace::libunwind::trace::hbc6889f168b90e7c
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:   0x8ecdf0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6b4acd9a46aa8f0c
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0x8ecdf0 - std::sys_common::backtrace::_print_fmt::h033fc597943e2bfa
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:67:5
   3:   0x8ecdf0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8bd447ee496d5cbd
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:46:22
   4:   0x911824 - core::fmt::write::h7a2ad6bdb88907e5
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/fmt/mod.rs:1092:17
   5:   0x8e5dbc - std::io::Write::write_fmt::h3362737d9f8ebaaf
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/io/mod.rs:1572:15
   6:   0x8ef660 - std::sys_common::backtrace::_print::he65e5d8232c91424
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:49:5
   7:   0x8ef660 - std::sys_common::backtrace::print::hc169dc40953b8903
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:36:9
   8:   0x8ef660 - std::panicking::default_hook::{{closure}}::h1d6009380b16d804
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:208:50
   9:   0x8ef040 - std::panicking::default_hook::hb14d0a4242db4d16
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:225:9
  10:   0x8efcc0 - std::panicking::rust_panic_with_hook::h68ae2514f8e19614
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:591:17
  11:   0x8ef83c - std::panicking::begin_panic_handler::{{closure}}::hfa5f2d30ce42ab3d
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:497:13
  12:   0x8ed36c - std::sys_common::backtrace::__rust_end_short_backtrace::h72505eec24afa3e9
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/sys_common/backtrace.rs:141:18
  13:   0x8ef784 - rust_begin_unwind
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
  14:   0x4aba40 - core::panicking::panic_fmt::h3d7d43fb3491fcf5
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:92:14
  15:   0x4ab8c8 - core::option::expect_failed::h0e71e8cad6201177
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/option.rs:1321:5
  16:   0x4e071c - librespot::get_setup::h41a9ddeac04910d6
  17:   0x50f554 - librespot::main::{{closure}}::hfa4c1ce5ff26089e
  18:   0x4d6d00 - tokio::macros::scoped_tls::ScopedKey<T>::set::h89fc9930f2f2748b
  19:   0x558d50 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h1dc14487f5886a9b
  20:   0x4d7224 - tokio::runtime::Runtime::block_on::h48b90dcbc6dbfaf2
  21:   0x4e138c - librespot::main::h40c915158c674391
  22:   0x4f0b38 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb9623564c538b4d1
  23:   0x541f64 - std::rt::lang_start::{{closure}}::haa29c5189d7c8a91
  24:   0x8f01d4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h52b0935f928e040e
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:259:13
  25:   0x8f01d4 - std::panicking::try::do_call::h3828ab385b5b41e7
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:379:40
  26:   0x8f01d4 - std::panicking::try::h37954c625dffcd6f
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:343:19
  27:   0x8f01d4 - std::panic::catch_unwind::ha1c3996ef57c906b
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panic.rs:431:14
  28:   0x8f01d4 - std::rt::lang_start_internal::hfb33fd713416b5f7
                       at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/rt.rs:51:25
  29:   0x4e1508 - main
  30: 0x76c5c718 - __libc_start_main
```

**Comment by roderickvd** [comment]
Please try compiling from #821, the Alsa mixer is broken in current `dev`.

**Comment by roderickvd** [comment]
Good to hear! I'll merge that PR shortly.

**Comment by roderickvd** [comment]
By the way, unless you have some specific requirement to use Alsa softvol, I recommend that you use librespot's own softvol and default mixer. Nowadays that's completely transparant in 64-bit floating point, while the Alsa one has more conversions and greater error due to working in integer math.
