### ISSUE TITLE
AddOn shows "too much errors" and doesn't work

### ISSUE THREAD

**Issue by emc02** [librespot-org/librespot#991]
I've got an "too many errors" message on starting latest librespot Version (0.3.1) on LE 10.0.2.
I've got the same issue on LE 9, then made a fresh install yesterday to LE 10.0.2, librespot was working well and now the same error again.
How can this be solved? Log is attached below.

`Librespot: monitor started
2022-04-28 14:12:49.120 T:1181     INFO <general>: Librespot: ['librespot', '--backend', 'pulseaudio', '--bitrate', '320', '--cache', 'cache', '--device', 'librespot', '--device-type', 'TV', '--disable-audio-cache', '--name', 'Librespot@KODI', '--notify-kodi', '--autoplay']
2022-04-28 14:12:49.240 T:1175     INFO <general>: SETTINGS: set_keyboard_layout # de
2022-04-28 14:12:49.240 T:1175     INFO <general>: SETTINGS: set_keyboard_layout # loadkmap < `ls -1 /usr/lib/keymaps/*/de.bmap`
2022-04-28 14:12:49.251 T:1181     INFO <general>: Librespot: loaded module-null-sink sink_name=librespot
2022-04-28 14:12:49.253 T:1133  WARNING <general>: Pulseaudio module module-allow-passthrough not loaded - opening PT devices might fail
2022-04-28 14:12:49.261 T:1133     INFO <general>: Found 2 Lists of Devices
2022-04-28 14:12:49.262 T:1133     INFO <general>: Enumerated PULSE devices:
2022-04-28 14:12:49.262 T:1133     INFO <general>:     Device 1
2022-04-28 14:12:49.262 T:1133     INFO <general>:         m_deviceName      : Default
2022-04-28 14:12:49.262 T:1133     INFO <general>:         m_displayName     : Default
2022-04-28 14:12:49.262 T:1133     INFO <general>:         m_displayNameExtra: Bluetooth Audio (PULSEAUDIO)
2022-04-28 14:12:49.262 T:1133     INFO <general>:         m_deviceType      : AE_DEVTYPE_PCM
2022-04-28 14:12:49.262 T:1133     INFO <general>:         m_channels        : FL, FR
2022-04-28 14:12:49.262 T:1133     INFO <general>:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2022-04-28 14:12:49.262 T:1133     INFO <general>:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
2022-04-28 14:12:49.262 T:1133     INFO <general>:         m_streamTypes     : No passthrough capabilities
2022-04-28 14:12:49.271 T:1133  WARNING <general>: Pulseaudio module module-allow-passthrough not loaded - opening PT devices might fail
2022-04-28 14:12:49.282 T:1133     INFO <general>: Found 2 Lists of Devices
2022-04-28 14:12:49.282 T:1133     INFO <general>: Enumerated PULSE devices:
2022-04-28 14:12:49.282 T:1133     INFO <general>:     Device 1
2022-04-28 14:12:49.288 T:1133     INFO <general>:         m_deviceName      : Default
2022-04-28 14:12:49.288 T:1133     INFO <general>:         m_displayName     : Default
2022-04-28 14:12:49.289 T:1133     INFO <general>:         m_displayNameExtra: Bluetooth Audio (PULSEAUDIO)
2022-04-28 14:12:49.296 T:1133     INFO <general>:         m_deviceType      : AE_DEVTYPE_PCM
2022-04-28 14:12:49.296 T:1133     INFO <general>:         m_channels        : FL, FR
2022-04-28 14:12:49.296 T:1133     INFO <general>:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2022-04-28 14:12:49.296 T:1133     INFO <general>:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
2022-04-28 14:12:49.296 T:1133     INFO <general>:         m_streamTypes     : No passthrough capabilities
2022-04-28 14:12:49.318 T:1181     INFO <general>: Librespot: loaded module-rtp-send destination_ip=127.0.0.1 port=24642 source=librespot.monitor
2022-04-28 14:12:49.357 T:1181     INFO <general>: Librespot: suspended sink 1
2022-04-28 14:12:49.370 T:1229     INFO <general>: Librespot: librespot thread started
2022-04-28 14:12:49.408 T:1229     INFO <general>: Librespot: librespot started
2022-04-28 14:12:49.495 T:1229     INFO <general>: Librespot: [2022-04-28T12:12:49Z INFO  librespot] librespot 0.3.1 1d5c210b2d (Built on 2021-12-24, Build ID: 9ivxgKm5, Profile: release)
2022-04-28 14:12:49.555 T:1229     INFO <general>: Librespot: *** WARNING *** The program 'librespot' uses the Apple Bonjour compatibility layer of Avahi.
2022-04-28 14:12:49.555 T:1229     INFO <general>: Librespot: *** WARNING *** Please fix your application to use the native API of Avahi!
2022-04-28 14:12:49.555 T:1229     INFO <general>: Librespot: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2022-04-28 14:12:49.573 T:1229     INFO <general>: Librespot: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DNSError(Unknown)', discovery/src/lib.rs:115:18
2022-04-28 14:12:49.621 T:1229     INFO <general>: Librespot: suspended sink 1
2022-04-28 14:12:49.621 T:1229     INFO <general>: Librespot: event panic 1/3
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:    0:   0x88d4a8 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:    1:   0x8b5c60 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:    2:   0x886698 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:    3:   0x88fc00 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:    4:   0x88f5a0 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:    5:   0x8902ec - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:    6:   0x88fdc4 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:    7:   0x88da60 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:    8:   0x88fd0c - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:    9:   0x45c1e4 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:   10:   0x45c2b8 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:   11:   0x54f390 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:   12:   0x4c1e00 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:   13:   0x497754 - <unknown>
2022-04-28 14:12:49.623 T:1229     INFO <general>: Librespot:   14:   0x4fc200 - <unknown>
2022-04-28 14:12:49.624 T:1229     INFO <general>: Librespot:   15:   0x488afc - <unknown>
2022-04-28 14:12:49.624 T:1229     INFO <general>: Librespot:   16:   0x50a744 - <unknown>
2022-04-28 14:12:49.624 T:1229     INFO <general>: Librespot:   17:   0x49f3a8 - <unknown>
2022-04-28 14:12:49.624 T:1229     INFO <general>: Librespot:   18:   0x4edec0 - <unknown>
2022-04-28 14:12:49.624 T:1229     INFO <general>: Librespot:   19:   0x890918 - <unknown>
2022-04-28 14:12:49.624 T:1229     INFO <general>: Librespot:   20:   0x50a8dc - main
2022-04-28 14:12:49.708 T:1229     INFO <general>: Librespot: suspended sink 1
2022-04-28 14:12:49.714 T:1229     INFO <general>: Librespot: librespot stopped
2022-04-28 14:12:49.743 T:1229     INFO <general>: Librespot: librespot started
2022-04-28 14:12:49.743 T:1229     INFO <general>: Librespot: [2022-04-28T12:12:49Z INFO  librespot] librespot 0.3.1 1d5c210b2d (Built on 2021-12-24, Build ID: 9ivxgKm5, Profile: release)
2022-04-28 14:12:49.765 T:1229     INFO <general>: Librespot: *** WARNING *** The program 'librespot' uses the Apple Bonjour compatibility layer of Avahi.
2022-04-28 14:12:49.765 T:1229     INFO <general>: Librespot: *** WARNING *** Please fix your application to use the native API of Avahi!
2022-04-28 14:12:49.765 T:1229     INFO <general>: Librespot: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2022-04-28 14:12:49.779 T:1229     INFO <general>: Librespot: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DNSError(Unknown)', discovery/src/lib.rs:115:18
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot: suspended sink 1
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot: event panic 2/3
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot:    0:   0xd2d4a8 - <unknown>
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot:    1:   0xd55c60 - <unknown>
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot:    2:   0xd26698 - <unknown>
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot:    3:   0xd2fc00 - <unknown>
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot:    4:   0xd2f5a0 - <unknown>
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot:    5:   0xd302ec - <unknown>
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot:    6:   0xd2fdc4 - <unknown>
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot:    7:   0xd2da60 - <unknown>
2022-04-28 14:12:49.871 T:1229     INFO <general>: Librespot:    8:   0xd2fd0c - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:    9:   0x8fc1e4 - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   10:   0x8fc2b8 - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   11:   0x9ef390 - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   12:   0x961e00 - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   13:   0x937754 - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   14:   0x99c200 - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   15:   0x928afc - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   16:   0x9aa744 - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   17:   0x93f3a8 - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   18:   0x98dec0 - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   19:   0xd30918 - <unknown>
2022-04-28 14:12:49.872 T:1229     INFO <general>: Librespot:   20:   0x9aa8dc - main
2022-04-28 14:12:49.960 T:1229     INFO <general>: Librespot: suspended sink 1
2022-04-28 14:12:49.971 T:1229     INFO <general>: Librespot: librespot stopped
2022-04-28 14:12:50.029 T:1229     INFO <general>: Librespot: librespot started
2022-04-28 14:12:50.030 T:1229     INFO <general>: Librespot: [2022-04-28T12:12:50Z INFO  librespot] librespot 0.3.1 1d5c210b2d (Built on 2021-12-24, Build ID: 9ivxgKm5, Profile: release)
2022-04-28 14:12:50.040 T:1229     INFO <general>: Librespot: *** WARNING *** The program 'librespot' uses the Apple Bonjour compatibility layer of Avahi.
2022-04-28 14:12:50.043 T:1229     INFO <general>: Librespot: *** WARNING *** Please fix your application to use the native API of Avahi!
2022-04-28 14:12:50.043 T:1229     INFO <general>: Librespot: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2022-04-28 14:12:50.049 T:1229     INFO <general>: Librespot: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DNSError(Unknown)', discovery/src/lib.rs:115:18
2022-04-28 14:12:50.104 T:1229     INFO <general>: Librespot: suspended sink 1
2022-04-28 14:12:50.104 T:1229     INFO <general>: Librespot: event panic 3/3
2022-04-28 14:12:50.104 T:1229     INFO <general>: Librespot:    0:   0xffd4a8 - <unknown>
2022-04-28 14:12:50.104 T:1229     INFO <general>: Librespot:    1:  0x1025c60 - <unknown>
2022-04-28 14:12:50.104 T:1229     INFO <general>: Librespot:    2:   0xff6698 - <unknown>
2022-04-28 14:12:50.104 T:1229     INFO <general>: Librespot:    3:   0xfffc00 - <unknown>
2022-04-28 14:12:50.104 T:1229     INFO <general>: Librespot:    4:   0xfff5a0 - <unknown>
2022-04-28 14:12:50.104 T:1229     INFO <general>: Librespot:    5:  0x10002ec - <unknown>
2022-04-28 14:12:50.104 T:1229     INFO <general>: Librespot:    6:   0xfffdc4 - <unknown>
2022-04-28 14:12:50.104 T:1229     INFO <general>: Librespot:    7:   0xffda60 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:    8:   0xfffd0c - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:    9:   0xbcc1e4 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   10:   0xbcc2b8 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   11:   0xcbf390 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   12:   0xc31e00 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   13:   0xc07754 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   14:   0xc6c200 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   15:   0xbf8afc - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   16:   0xc7a744 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   17:   0xc0f3a8 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   18:   0xc5dec0 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   19:  0x1000918 - <unknown>
2022-04-28 14:12:50.105 T:1229     INFO <general>: Librespot:   20:   0xc7a8dc - main
2022-04-28 14:12:50.200 T:1229     INFO <general>: Librespot: suspended sink 1
2022-04-28 14:12:50.205 T:1229     INFO <general>: Librespot: librespot stopped
2022-04-28 14:12:50.206 T:1229     INFO <general>: Librespot: librespot thread stopped
2022-04-28 14:12:50.383 T:1181     INFO <general>: Librespot: librespot died
2022-04-28 14:12:50.500 T:1181     INFO <general>: Librespot: unloaded module-rtp-send destination_ip=127.0.0.1 port=24642 source=librespot.monitor`

**Comment by shanemeagher** [comment]
Probably best to wait for a response here: https://forum.libreelec.tv/thread/8438-librespot-addon/?postID=169161#post169161

`Librespot: thread 'main' panicked at 'called Result::unwrap() on an Err value: DNSError(Unknown)', discovery/src/lib.rs:115:18`

Looks similar to issue #985 which might be a problem with `avahi `on LE.

**Comment by roderickvd** [comment]
That does seem so. I am going to close this issue for now, as it seems to be with LibreELEC and not with us.

**Comment by emc02** [comment]
Thanks, that helped and it's working again. "ZeroConfig" was disabled. I enabled it and now it works. Would be nice to see a "better" Message in librespot, but it's ok. Thanks for your work here!
